[package]
name = "nrf70"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
align-data = "0.1.0"
defmt = "1.0.1"
embassy-futures = "0.1.2"
embassy-net-driver-channel = "0.4.0"
embassy-sync = "0.8.0"
embassy-time = "0.5.1"
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
num_enum = { version = "0.7.4", default-features = false }
