//! Driver for the Nordic nRF7002 Wi-Fi 6 companion chip, on embassy.
//!
//! [`new`] turns the chip on and returns its three parts: the [`NetDriver`] for embassy-net, the
//! [`Control`] the application drives it with, and the [`Runner`], which owns the chip and runs in
//! a task of its own.
//!
//! The runner's code is split by concern. `rpu.rs` is the host interface to the chip (its memory,
//! queues, interrupt and sleep) and `command.rs` the commands it takes; `boot.rs` turns the chip
//! on and off; `data.rs` carries the frames; `station.rs` joins networks, with `wpa2.rs` and
//! `supplicant.rs` for WPA2 and `wpa3.rs`, `sae.rs` and `pmksa.rs` for WPA3; `ap.rs` runs the
//! access point, with `authenticator.rs` and `ap/wpa3.rs`. Both sides share `ieee80211.rs` (element
//! IDs, status and reason codes), `rsn.rs` (RSN elements and suites), `eapol.rs` (EAPOL-Key frames)
//! and `crypto.rs` (the key derivations). This file has the runner's loop: the requests from
//! [`Control`] and the dispatch of the RPU's events.

#![no_std]
#![deny(unused_must_use)]
#![allow(async_fn_in_trait)]

use core::mem::{align_of, size_of, zeroed};
use core::slice;

use control::{Request, ScanEvent, Shared};
use defmt::{assert, panic, *};
use embassy_futures::select::{select3, Either3};
use embassy_net_driver_channel as ch;
use embassy_net_driver_channel::driver::LinkState;
use embassy_time::{with_deadline, with_timeout, Duration, Instant};
use embedded_hal::digital::{InputPin, OutputPin};
use embedded_hal_async::digital::Wait;
use rpu::{Rpu, MAX_TX_TOKENS};
use station::ConnState;

#[allow(unused)]
#[allow(non_camel_case_types)]
#[allow(non_snake_case)]
#[allow(clippy::all)] // generated by bindgen
mod c {
    include!("../fw/bindings.rs");
    pub const RPU_MCU_CORE_INDIRECT_BASE: u32 = 0xC0000000;
    pub const RX_BUF_HEADROOM: u32 = 4;
}

#[cfg(feature = "ap")]
mod ap;
#[cfg(all(feature = "ap", feature = "wpa2"))]
mod authenticator;
mod boot;
mod bus;
mod command;
mod control;
#[cfg(feature = "wpa2")]
mod crypto;
mod data;
#[cfg(feature = "wpa2")]
mod eapol;
mod ieee80211;
#[cfg(feature = "wpa3")]
mod pmksa;
mod rpu;
#[cfg(feature = "wpa2")]
mod rsn;
#[cfg(feature = "wpa3")]
mod sae;
mod station;
#[cfg(feature = "wpa2")]
mod supplicant;
#[cfg(feature = "wpa2")]
mod wpa2;
#[cfg(feature = "wpa3")]
mod wpa3;

#[cfg(feature = "ap")]
pub use ap::ApError;
pub use bus::{Bus, SpiBus};
pub use control::{Band, BssInfo, ConnectError, Control, LinkStatus, PowerSave, Scanner, Security};
#[cfg(feature = "wpa2")]
pub use wpa2::wpa2_psk;

const MTU: usize = 1514;

/// How long the RPU gets to answer the init command and interface changes.
const EVENT_TIMEOUT: Duration = Duration::from_secs(5);
/// A scan covers every 2.4 GHz and 5 GHz channel, which takes a few seconds.
const SCAN_TIMEOUT: Duration = Duration::from_secs(30);
/// The RPU raises HOST_IRQ when it has events. The event queue is read this often as well, in
/// case an interrupt goes missing.
const IRQ_POLL_PERIOD: Duration = Duration::from_millis(50);
/// Longest event the driver reassembles. Longer ones are drained and dropped.
const MAX_EVENT_LEN: usize = 4096;

pub struct State {
    shared: Shared,
    ch: ch::State<MTU, 4, 4>,
    /// Where the runner reads the RPU's events. It lives here, once, rather than in the runner's
    /// future, where each wait for an event had a buffer of its own.
    events: [u32; MAX_EVENT_LEN / 4],
    #[cfg(feature = "ap")]
    ap_storage: ap::Storage,
    /// The PMKs of the WPA3 access points joined.
    #[cfg(feature = "wpa3")]
    pmksa_cache: wpa3::PmksaCache,
}

impl State {
    pub fn new() -> Self {
        Self {
            ch: ch::State::new(),
            events: [0; MAX_EVENT_LEN / 4],
            #[cfg(feature = "ap")]
            ap_storage: ap::Storage::new(),
            #[cfg(feature = "wpa3")]
            pmksa_cache: wpa3::PmksaCache::new(),
            shared: Shared::new(),
        }
    }
}

impl Default for State {
    fn default() -> Self {
        Self::new()
    }
}

pub type NetDriver<'a> = ch::Device<'a, MTU>;

/// Board settings, which the nRF Connect SDK takes from the devicetree and Kconfig.
#[derive(Clone, Copy, Debug, defmt::Format)]
pub struct Config {
    /// The highest TX power the board may use. The RPU uses the lower of this and the chip's own
    /// limits.
    pub max_tx_power: TxPowerCeiling,
    /// ISO 3166-1 alpha-2 country code of the regulatory domain, `*b"00"` for the world domain.
    pub country_code: [u8; 2],
    /// Lets the RPU sleep whenever it has nothing to do (the SDK's low power mode). The driver
    /// then wakes it up before each bus access, which costs a few milliseconds after an idle time,
    /// and lets it sleep again once the bus has been idle for 10 ms.
    ///
    /// The RPU only finds time to sleep while it does not have to listen: with 802.11 power save
    /// on ([`Control::set_power_save`]), or while not connected.
    pub low_power: bool,
}

/// Highest TX power per band and modulation, in dBm (the devicetree's `wifi-max-tx-pwr-*`).
#[derive(Clone, Copy, Debug, defmt::Format)]
pub struct TxPowerCeiling {
    pub dsss_2g: u8,
    pub mcs0_2g: u8,
    pub mcs7_2g: u8,
    pub mcs0_5g_low: u8,
    pub mcs7_5g_low: u8,
    pub mcs0_5g_mid: u8,
    pub mcs7_5g_mid: u8,
    pub mcs0_5g_high: u8,
    pub mcs7_5g_high: u8,
}

pub async fn new<'a, BUS, IN, OUT>(
    state: &'a mut State,
    bus: BUS,
    bucken: OUT,
    iovdd_ctl: OUT,
    host_irq: IN,
    config: Config,
) -> (NetDriver<'a>, Control<'a>, Runner<'a, BUS, IN, OUT>)
where
    BUS: Bus,
    IN: InputPin + Wait,
    OUT: OutputPin,
{
    let (ch_runner, device) = ch::new(&mut state.ch, ch::driver::HardwareAddress::Ethernet([0; 6]));
    let state_ch = ch_runner.state_runner();

    let mut runner = Runner {
        ch: ch_runner,
        state_ch,
        shared: &state.shared,
        rpu: Rpu::new(bus, config.low_power),
        bucken,
        iovdd_ctl,
        host_irq,
        config,
        powered: false,
        power_save: false,
        scan_deadline: None,
        sta: station::State::new(),
        #[cfg(feature = "wpa2")]
        wpa2: wpa2::State::new(),
        #[cfg(feature = "wpa3")]
        wpa3: wpa3::State::new(&mut state.pmksa_cache),
        carrier_on: false,
        events: &mut state.events,
        init_done: false,
        interface_state_set: false,
        link_up: false,
        tx_tokens_busy: 0,
        #[cfg(feature = "ap")]
        ap: ap::State::new(&mut state.ap_storage),
    };
    runner.init().await;

    let control = Control { shared: &state.shared };

    (device, control, runner)
}

fn sliceit<T>(t: &T) -> &[u8] {
    unsafe { slice::from_raw_parts(t as *const _ as _, size_of::<T>()) }
}

fn unsliceit2<T>(t: &[u8]) -> (&T, &[u8]) {
    assert!(t.len() >= size_of::<T>());
    assert!((t.as_ptr() as usize).is_multiple_of(align_of::<T>()));
    (unsafe { &*(t.as_ptr() as *const T) }, &t[size_of::<T>()..])
}

fn unsliceit<T>(t: &[u8]) -> &T {
    unsliceit2(t).0
}

fn slice8(x: &[u32]) -> &[u8] {
    let len = x.len() * 4;
    unsafe { slice::from_raw_parts(x.as_ptr() as _, len) }
}

fn slice8_mut(x: &mut [u32]) -> &mut [u8] {
    let len = x.len() * 4;
    unsafe { slice::from_raw_parts_mut(x.as_mut_ptr() as _, len) }
}

/// An event from the RPU, as far as the runner needs to tell them apart.
enum Event<'b> {
    /// A system event, by `sys_events` number.
    Sys(u32),
    /// A UMAC event, by `umac_events` number, with the whole message (which starts with its
    /// `umac_hdr`).
    Umac(u32, &'b [u8]),
    /// Data path events: the whole message body, one or more events that each start with a
    /// `umac_head`.
    Data(&'b [u8]),
    /// Any other message type.
    Other(u32),
}

fn parse_event(buf: &[u8]) -> Event<'_> {
    let (msg, body) = unsliceit2::<c::host_rpu_msg>(buf);
    let msg_type = msg.type_ as u32;
    match c::host_rpu_msg_type::try_from(msg_type) {
        Ok(c::host_rpu_msg_type::HOST_RPU_MSG_TYPE_SYSTEM) => Event::Sys(unsliceit::<c::sys_head>(body).cmd_event),
        Ok(c::host_rpu_msg_type::HOST_RPU_MSG_TYPE_UMAC) => Event::Umac(unsliceit::<c::umac_hdr>(body).cmd_evnt, body),
        Ok(c::host_rpu_msg_type::HOST_RPU_MSG_TYPE_DATA) => Event::Data(body),
        _ => Event::Other(msg_type),
    }
}

pub struct Runner<'a, BUS: Bus, IN: InputPin + Wait, OUT: OutputPin> {
    ch: ch::Runner<'a, MTU>,
    state_ch: ch::StateRunner<'a>,
    shared: &'a Shared,

    rpu: Rpu<BUS>,
    bucken: OUT,
    iovdd_ctl: OUT,
    host_irq: IN,

    /// The board settings, for each time the chip is turned on.
    config: Config,
    /// The chip is on: not between [`Control::power_off`] and [`Control::power_on`].
    powered: bool,
    /// 802.11 power save as last asked for, to restore it when the chip is turned on again.
    power_save: bool,

    /// Set while a display scan is running, so a lost one does not block the next.
    scan_deadline: Option<Instant>,

    /// The network joined or being joined.
    sta: station::State,
    /// The key handshakes of a WPA2 network.
    #[cfg(feature = "wpa2")]
    wpa2: wpa2::State,
    /// The SAE exchange of a WPA3 network, and the PMKs of earlier ones.
    #[cfg(feature = "wpa3")]
    wpa3: wpa3::State<'a>,
    /// The RPU reported the carrier on (`CMD_CARRIER_ON`).
    carrier_on: bool,
    /// The buffer events are read into, from [`State`]. An empty slice while it is in use.
    events: &'a mut [u32],
    /// The RPU reported its initialisation done (`EVENT_INIT_DONE`).
    init_done: bool,
    /// The RPU answered the last change of the interface's state (`UMAC_EVENT_IFFLAGS_STATUS`).
    interface_state_set: bool,
    /// The link as reported to embassy-net.
    link_up: bool,
    /// TX tokens handed to the RPU and not yet reported done, one bit each.
    tx_tokens_busy: u16,
    /// The access point.
    #[cfg(feature = "ap")]
    ap: ap::State<'a>,
}

/// What the runner asks of `wpa3.rs`, in a build without the `wpa3` feature: nothing.
#[cfg(not(feature = "wpa3"))]
impl<BUS: Bus, IN: InputPin + Wait, OUT: OutputPin> Runner<'_, BUS, IN, OUT> {
    fn sae_start(&mut self, _bss: &station::Bss, _cmd: &mut c::umac_cmd_auth) {}

    async fn sae_frame(&mut self, _event: &c::umac_event_mlme) -> bool {
        false
    }

    fn pmksa_failed(&mut self, _error: &ConnectError) -> Option<station::Bss> {
        None
    }
}

/// What the runner asks of `wpa2.rs`, in a build without the `wpa2` feature: nothing.
#[cfg(not(feature = "wpa2"))]
impl<BUS: Bus, IN: InputPin + Wait, OUT: OutputPin> Runner<'_, BUS, IN, OUT> {
    const EAPOL_TX_TOKENS: u32 = 0;

    fn set_station_address(&mut self, _mac_addr: [u8; 6]) {}

    fn secure_association(&mut self, _bss: &station::Bss, _info: &mut c::connect_common_info) {}

    fn handshake_expected(&self) -> bool {
        false
    }

    async fn rx_eapol(&mut self, eapol: data::RxEapol) {
        match eapol {}
    }

    async fn frame_sent(&mut self, _token: usize) {}

    async fn check_handshake_timers(&mut self) {}

    fn handshake_deadline(&self) -> Option<Instant> {
        None
    }

    fn forget_keys(&mut self) {}
}

/// What the runner asks of `ap.rs`, in a build without the `ap` feature: nothing.
#[cfg(not(feature = "ap"))]
impl<BUS: Bus, IN: InputPin + Wait, OUT: OutputPin> Runner<'_, BUS, IN, OUT> {
    fn ap_running(&self) -> bool {
        false
    }

    fn ap_has_room(&self) -> bool {
        true
    }

    fn set_ap_address(&mut self, _mac_addr: [u8; 6]) {}

    fn forget_ap(&mut self) {}

    async fn ap_hold(&mut self, _frame: &mut [u32], _len: usize) -> bool {
        false
    }

    async fn ap_deliver(&mut self) {}

    async fn ap_check_timeouts(&mut self) {}

    fn ap_frame_queued(&mut self, _token: usize, _to: &[u8]) {}

    fn ap_frame_done(&mut self, _token: usize, _acked: bool) {}

    fn ap_seen(&mut self, _src: &[u8; 6]) {}

    fn ap_deadline(&self) -> Option<Instant> {
        None
    }
}

impl<'a, BUS: Bus, IN: InputPin + Wait, OUT: OutputPin> Runner<'a, BUS, IN, OUT> {
    async fn set_power_save(&mut self, enabled: bool) {
        let mut cmd: c::umac_cmd_set_power_save = unsafe { zeroed() };
        cmd.info.ps_state = if enabled {
            c::ps_state::PS_ENABLED
        } else {
            c::ps_state::PS_DISABLED
        } as _;
        self.rpu.send_cmd(&mut cmd).await;
    }

    pub async fn run(&mut self) -> ! {
        info!("running...");

        let mut tx_frame = [0u32; MTU.div_ceil(4)];

        let mut poll_at = Instant::now();

        loop {
            // HOST_IRQ is high while the RPU has events that were not acknowledged. In low power
            // mode the queue is read then only: a poll would wake the RPU up each time.
            let irq = self.powered && self.host_irq.is_high().unwrap_or(true);
            if irq || (self.powered && !self.config.low_power && Instant::now() >= poll_at) {
                let events = self.service_events().await;
                if events > 0 && !irq {
                    debug!("{} events found without an interrupt", events);
                }
                poll_at = Instant::now() + IRQ_POLL_PERIOD;
            }
            self.check_conn_timeout().await;
            self.check_handshake_timers().await;
            self.ap_deliver().await;
            self.ap_check_timeouts().await;
            self.rpu.ps_sleep().await;

            let shared = self.shared;
            // With WPA2, one token stays free for the supplicant.
            let data_tx_tokens = MAX_TX_TOKENS as u32 - Self::EAPOL_TX_TOKENS;
            let can_tx = self.link_up && self.tx_tokens_busy.count_ones() < data_tx_tokens && self.ap_has_room();
            // What the loop has to come back for without an interrupt.
            let wake_at = [
                (self.powered && !self.config.low_power).then_some(poll_at),
                (self.config.low_power && self.rpu.awake).then_some(self.rpu.idle_at),
                self.sta.deadline,
                self.handshake_deadline(),
                self.ap_deadline(),
            ]
            .into_iter()
            .flatten()
            .min();
            let ch = &mut self.ch;
            let host_irq = &mut self.host_irq;
            let powered = self.powered;
            let irq = async {
                // HOST_IRQ means nothing while the chip is off.
                let irq = async {
                    if powered {
                        drop(host_irq.wait_for_high().await)
                    } else {
                        core::future::pending().await
                    }
                };
                match wake_at {
                    Some(at) => drop(with_deadline(at, irq).await),
                    None => irq.await,
                }
            };
            let tx = async {
                if can_tx {
                    ch.tx_buf().await
                } else {
                    core::future::pending().await
                }
            };
            // The interrupt comes last: its events are read at each turn of the loop anyway, and
            // a busy receiver must not keep a request or a frame to send waiting.
            match select3(shared.requests.receive(), tx, irq).await {
                Either3::First(request) => self.handle_request(&request).await,
                Either3::Second(frame) => {
                    let len = frame.len();
                    slice8_mut(&mut tx_frame)[..len].copy_from_slice(frame);
                    self.ch.tx_done();
                    self.send_queued_frames(&mut tx_frame, len).await;
                }
                Either3::Third(_) => {}
            }
        }
    }

    /// Handles the events the RPU has queued (NCS `hal_rpu_irq_process`). Returns how many events
    /// there were.
    ///
    /// The interrupt is acknowledged before the queue is read: an event queued after the
    /// acknowledgement raises it again, and one queued before is read here. (Acknowledged after
    /// the queue had been read empty, as NCS does, an event queued in between lost its interrupt,
    /// and the queue had to be read once more.) The watchdog, the other source of the interrupt,
    /// is checked only when the interrupt came with nothing queued: each status read is a bus
    /// transaction, and there are thousands of interrupts a second while data flows.
    async fn service_events(&mut self) -> usize {
        let irq = self.host_irq.is_high().unwrap_or(false);
        if irq {
            self.rpu.irq_ack().await;
        }
        let buf = self.take_event_buffer();
        let mut events = 0;
        while let Some(len) = self.rpu.event_next(buf).await {
            events += 1;
            if len > 0 {
                self.handle_event(slice8(buf), len).await;
            }
        }
        self.events = buf;
        self.rpu.irq_pending_ack = false;
        if irq && events == 0 && self.rpu.irq_watchdog_check().await {
            debug!("RPU watchdog interrupt");
            self.rpu.irq_watchdog_ack().await;
        }
        events
    }

    /// What a request gets while the chip is off.
    async fn handle_request_off(&mut self, request: &Request) {
        match request {
            Request::Scan => {
                warn!("scan refused: the chip is off");
                self.push_scan_event(ScanEvent::Aborted);
            }
            Request::Connect(..) => {
                let _ = self.shared.connect_result.try_send(Err(ConnectError::PoweredOff));
            }
            Request::LinkStatus => {
                let _ = self.shared.link_status.try_send(None);
            }
            Request::SetPowerSave(enabled) => self.power_save = *enabled,
            Request::PowerSave => {
                let _ = self.shared.power_save.try_send(None);
            }
            Request::PowerOff => {
                let _ = self.shared.power_done.try_send(());
            }
            Request::PowerOn => {
                self.init().await;
                let _ = self.shared.power_done.try_send(());
            }
            #[cfg(feature = "ap")]
            Request::StartAp(_) => {
                let _ = self.shared.ap_result.try_send(Err(ApError::PoweredOff));
            }
            #[cfg(feature = "ap")]
            Request::StopAp => {
                let _ = self.shared.ap_result.try_send(Ok(()));
            }
        }
    }

    async fn handle_request(&mut self, request: &Request) {
        if !self.powered {
            return self.handle_request_off(request).await;
        }
        let scan_running = self.scan_deadline.is_some_and(|deadline| Instant::now() < deadline);
        let connecting = !matches!(self.sta.conn, ConnState::Idle | ConnState::Connected);
        match request {
            Request::Scan => {
                if scan_running || connecting || self.ap_running() {
                    warn!("scan refused: a scan, a connection or the access point is in progress");
                    self.push_scan_event(ScanEvent::Aborted);
                    return;
                }
                self.scan_deadline = Some(Instant::now() + SCAN_TIMEOUT);
                self.trigger_scan().await;
            }
            Request::SetPowerSave(enabled) => {
                self.power_save = *enabled;
                self.set_power_save(*enabled).await;
            }
            Request::PowerOff => {
                self.power_off().await;
                let _ = self.shared.power_done.try_send(());
            }
            Request::PowerOn => {
                let _ = self.shared.power_done.try_send(());
            }
            Request::PowerSave => {
                let mut cmd: c::umac_cmd_get_power_save_info = unsafe { zeroed() };
                self.rpu.send_cmd(&mut cmd).await;
            }
            #[cfg(feature = "ap")]
            Request::StartAp(settings) => {
                let result = self.start_ap(settings).await;
                let _ = self.shared.ap_result.try_send(result);
            }
            #[cfg(feature = "ap")]
            Request::StopAp => {
                self.stop_ap().await;
                let _ = self.shared.ap_result.try_send(Ok(()));
            }
            Request::LinkStatus => match self.sta.bss {
                Some(bss) if self.sta.conn == ConnState::Connected => {
                    self.get_station(bss).await;
                    self.sta.link_status_requested = true;
                }
                _ => {
                    let _ = self.shared.link_status.try_send(None);
                }
            },
            Request::Connect(ssid, credentials) => {
                if scan_running || connecting || self.ap_running() {
                    let _ = self.shared.connect_result.try_send(Err(ConnectError::Busy));
                    return;
                }
                self.join(*ssid, credentials).await;
            }
        }
    }

    /// Handles one event. `buf` holds it from its start and `len` is its length; `buf` may be
    /// longer, because some events are shorter than the structure that describes them.
    async fn handle_event(&mut self, buf: &[u8], len: usize) {
        match parse_event(buf) {
            Event::Sys(id) => match c::sys_events::try_from(id) {
                Ok(c::sys_events::EVENT_INIT_DONE) => self.init_done = true,
                Ok(event) => debug!("sys event {}", event as u32),
                Err(_) => warn!("unknown sys event type {:08x}", id),
            },
            Event::Umac(id, body) => self.handle_umac_event(id, body).await,
            Event::Data(body) => {
                // One message can carry several data events, each giving its own length (NCS
                // `nrf_wifi_sys_fmac_event_callback`).
                let mut left = len.saturating_sub(size_of::<c::host_rpu_msg>()).min(body.len());
                let mut body = body;
                while left >= size_of::<c::umac_head>() {
                    let head: &c::umac_head = unsliceit(body);
                    let (id, event_len) = (head.cmd, head.len as usize);
                    if event_len == 0 || event_len > left {
                        warn!("malformed data event {}, length {}", id, event_len);
                        break;
                    }
                    self.handle_data_event(id, body).await;
                    body = &body[event_len..];
                    left -= event_len;
                }
            }
            Event::Other(msg_type) => warn!("unknown event type {:08x}", msg_type),
        }
    }

    async fn handle_data_event(&mut self, id: u32, body: &[u8]) {
        match c::umac_data_commands::try_from(id) {
            Ok(c::umac_data_commands::CMD_RX_BUFF) => self.handle_rx(body).await,
            Ok(c::umac_data_commands::CMD_TX_BUFF_DONE) => {
                let (done, statuses) = unsliceit2::<c::tx_buff_done>(body);
                let token = done.tx_desc_num as usize;
                // One status per frame of the token. A failed one is a frame the RPU gave up on:
                // the AP never acknowledged it, and it is lost.
                let statuses = statuses.get(..done.num_tx_status_code as usize).unwrap_or(&[]);
                let acked = statuses.iter().all(|&status| status as u32 == c::TX_STATUS_SUCCESS);
                if !acked {
                    debug!("frame of TX token {} not acknowledged", token);
                }
                if token < MAX_TX_TOKENS {
                    self.ap_frame_done(token, acked);
                    self.tx_tokens_busy &= !(1 << token);
                    self.frame_sent(token).await;
                } else {
                    warn!("TX done for invalid token {}", token);
                }
            }
            #[cfg(feature = "ap")]
            Ok(c::umac_data_commands::CMD_PM_MODE) => self.ap_power_save(body).await,
            #[cfg(feature = "ap")]
            Ok(c::umac_data_commands::CMD_PS_GET_FRAMES) => self.ap_get_frames(body).await,
            Ok(c::umac_data_commands::CMD_CARRIER_ON) => {
                debug!("carrier on");
                self.carrier_on = true;
                self.check_associated().await;
            }
            Ok(c::umac_data_commands::CMD_CARRIER_OFF) => {
                debug!("carrier off");
                // It names no access point: one that was left for the next one of the network
                // reports it after the next one is in hand, when the carrier is off already.
                if self.carrier_on {
                    self.carrier_on = false;
                    self.connection_lost().await;
                }
            }
            _ => debug!("unhandled data event {}", id),
        }
    }

    async fn handle_umac_event(&mut self, id: u32, body: &[u8]) {
        use c::umac_events::*;
        match c::umac_events::try_from(id) {
            Ok(UMAC_EVENT_TRIGGER_SCAN_START) => debug!("scan started"),
            Ok(UMAC_EVENT_SCAN_DONE) => {
                // Scans hand their results over only when asked for them.
                if self.sta.conn == ConnState::Scanning {
                    self.get_scan_results(c::scan_reason::SCAN_CONNECT).await;
                } else if self.scan_deadline.is_some() {
                    self.get_scan_results(c::scan_reason::SCAN_DISPLAY).await;
                }
            }
            Ok(UMAC_EVENT_SCAN_ABORTED) => {
                if self.sta.conn == ConnState::Scanning {
                    self.connect_failed(ConnectError::NotFound).await;
                } else {
                    self.scan_deadline = None;
                    self.push_scan_event(ScanEvent::Aborted);
                }
            }
            Ok(UMAC_EVENT_SCAN_DISPLAY_RESULT) => self.scan_display_results(unsliceit(body)),
            Ok(UMAC_EVENT_SCAN_RESULT) => self.handle_scan_result(body).await,
            Ok(UMAC_EVENT_AUTHENTICATE) => self.auth_event(unsliceit(body)).await,
            Ok(UMAC_EVENT_ASSOCIATE) => self.assoc_event(unsliceit(body)).await,
            Ok(UMAC_EVENT_GET_POWER_SAVE_INFO) => {
                let event: &c::umac_event_power_save_info = unsliceit(body);
                let (timeout, listen_interval) = (event.ps_timeout, event.listen_interval);
                debug!(
                    "power save: enabled {}, mode {}, extended {}, timeout {} ms, listen interval {}, exit strategy {}",
                    event.enabled, event.ps_mode, event.extended_ps, timeout, listen_interval, event.ps_exit_strategy
                );
                let _ = self.shared.power_save.try_send(Some(PowerSave {
                    enabled: event.enabled != 0,
                    timeout_ms: timeout,
                }));
            }
            // The station entry comes in the layout of a new station event.
            Ok(UMAC_EVENT_GET_STATION) => self.station_info(unsliceit(body)),
            #[cfg(feature = "ap")]
            Ok(UMAC_EVENT_NEW_STATION) if self.ap_running() => {
                let station = unsliceit::<c::umac_event_new_station>(body).mac_addr;
                debug!("station {:02x} added as peer", station);
            }
            #[cfg(feature = "ap")]
            Ok(UMAC_EVENT_DEL_STATION) if self.ap_running() => self.ap_station_removed(body).await,
            #[cfg(feature = "ap")]
            Ok(UMAC_EVENT_FRAME) => self.ap_frame(body).await,
            #[cfg(feature = "ap")]
            Ok(UMAC_EVENT_FRAME_TX_STATUS) => self.ap_frame_sent(body).await,
            #[cfg(feature = "ap")]
            Ok(UMAC_EVENT_SET_INTERFACE) => self.interface_type_set(body),
            #[cfg(feature = "ap")]
            Ok(UMAC_EVENT_COOKIE_RESP) => {}
            Ok(UMAC_EVENT_NEW_STATION) => {
                let peer = unsliceit::<c::umac_event_new_station>(body).mac_addr;
                self.peer_added(peer).await;
            }
            Ok(UMAC_EVENT_DEL_STATION) => {
                let peer = unsliceit::<c::umac_event_new_station>(body).mac_addr;
                self.peer_removed(peer).await;
            }
            Ok(
                UMAC_EVENT_DEAUTHENTICATE
                | UMAC_EVENT_DISASSOCIATE
                | UMAC_EVENT_UNPROT_DEAUTHENTICATE
                | UMAC_EVENT_UNPROT_DISASSOCIATE,
            ) => self.disconnect_event(id, unsliceit(body)).await,
            Ok(UMAC_EVENT_IFFLAGS_STATUS) => {
                let status = unsliceit::<c::umac_event_vif_state>(body).status;
                debug!("interface flags status {}", status);
                self.interface_state_set = true;
            }
            Ok(UMAC_EVENT_CMD_STATUS) => {
                let event: &c::umac_event_cmd_status = unsliceit(body);
                let (cmd, status) = (event.cmd_id, event.cmd_status);
                if status != 0 {
                    warn!("command {} failed with status {}", cmd, status);
                }
            }
            _ => debug!("unhandled UMAC event {}", id),
        }
    }

    /// Hands a batch of display scan results to the [`Scanner`].
    fn scan_display_results(&mut self, event: &c::umac_event_new_scan_display_results) {
        let count = (event.event_bss_count as usize).min(event.display_results.len());
        let seq = event.umac_hdr.seq;
        debug!("scan display results: seq {}, {} BSS", seq, count);
        for result in &event.display_results[..count] {
            self.push_scan_event(ScanEvent::Bss(BssInfo::from_display_result(result)));
        }
        // The last batch of results has a zero sequence number.
        if seq == 0 {
            self.scan_deadline = None;
            self.push_scan_event(ScanEvent::Done);
        }
    }

    fn push_scan_event(&mut self, event: ScanEvent) {
        if self.shared.scan_results.try_send(event).is_err() {
            warn!("scan result dropped, the scanner is not keeping up");
        }
    }

    fn set_link(&mut self, up: bool) {
        if up != self.link_up {
            self.link_up = up;
            self.state_ch
                .set_link_state(if up { LinkState::Up } else { LinkState::Down });
        }
    }

    /// Handles events until `done` holds, or `timeout` passes. Returns whether `done` held.
    async fn wait_until(&mut self, timeout: Duration, done: impl Fn(&Self) -> bool) -> bool {
        let buf = self.take_event_buffer();
        let held = with_timeout(timeout, async {
            while !done(self) {
                let len = self.next_event(buf).await;
                self.handle_event(slice8(buf), len).await;
            }
        })
        .await
        .is_ok();
        self.events = buf;
        held
    }

    /// The event buffer, taken from the runner while events are read into it and handled.
    fn take_event_buffer(&mut self) -> &'a mut [u32] {
        let buf = core::mem::take(&mut self.events);
        if buf.is_empty() {
            panic!("the event buffer is in use");
        }
        buf
    }

    /// Reads the next event into `buf` and returns its length, waiting for HOST_IRQ while the
    /// queue is empty.
    async fn next_event(&mut self, buf: &mut [u32]) -> usize {
        loop {
            match self.rpu.event_next(buf).await {
                Some(len) if len > 0 => return len,
                Some(_) => {}
                None => {
                    self.rpu.irq_service_end().await;
                    let _ = with_timeout(IRQ_POLL_PERIOD, self.host_irq.wait_for_rising_edge()).await;
                }
            }
        }
    }

    /// Starts a display scan (NCS `nrf_wifi_disp_scan_zep` without parameters). The zeroed
    /// parameters ask for an active scan of every channel of both bands, with the default dwell
    /// times.
    async fn trigger_scan(&mut self) {
        let mut cmd: c::umac_cmd_scan = unsafe { zeroed() };
        cmd.info.scan_reason = c::scan_reason::SCAN_DISPLAY as _;
        self.rpu.send_cmd(&mut cmd).await;
    }

    /// Asks for the results of a finished scan (NCS `nrf_wifi_sys_fmac_scan_res_get`).
    async fn get_scan_results(&mut self, reason: c::scan_reason) {
        let mut cmd: c::umac_cmd_get_scan_results = unsafe { zeroed() };
        cmd.scan_reason = reason as _;
        self.rpu.send_cmd(&mut cmd).await;
    }
}

#[cfg(test)]
pub(crate) mod tests {
    extern crate std;

    use core::assert;
    use std::vec::Vec;

    use super::*;

    /// The bytes of a hex string, which may have white space between them.
    #[cfg_attr(not(any(feature = "wpa2", feature = "ap")), allow(dead_code))]
    pub(crate) fn hex(s: &str) -> Vec<u8> {
        let s: Vec<u8> = s.bytes().filter(|b| !b.is_ascii_whitespace()).collect();
        s.chunks(2)
            .map(|pair| u8::from_str_radix(core::str::from_utf8(pair).unwrap(), 16).unwrap())
            .collect()
    }

    // The host has no RTT: defmt output goes nowhere.
    #[defmt::global_logger]
    struct NullLogger;

    unsafe impl defmt::Logger for NullLogger {
        fn acquire() {}
        unsafe fn flush() {}
        unsafe fn release() {}
        unsafe fn write(_bytes: &[u8]) {}
    }

    #[defmt::panic_handler]
    fn defmt_panic() -> ! {
        core::panic!("defmt panic")
    }

    defmt::timestamp!("");

    #[test]
    fn events_are_told_apart_by_message_type() {
        let mut buf = [0u32; 8];
        let words = [
            16, // host_rpu_msg_hdr.len
            0,  // host_rpu_msg_hdr.resubmit
            c::host_rpu_msg_type::HOST_RPU_MSG_TYPE_SYSTEM as u32,
            c::sys_events::EVENT_INIT_DONE as u32, // sys_head.cmd_event
        ];
        buf[..4].copy_from_slice(&words);
        assert!(matches!(
            parse_event(slice8(&buf)),
            Event::Sys(id) if id == c::sys_events::EVENT_INIT_DONE as u32
        ));

        buf[2] = c::host_rpu_msg_type::HOST_RPU_MSG_TYPE_DATA as u32;
        buf[3] = c::umac_data_commands::CMD_RX_BUFF as u32; // umac_head.cmd
        assert!(matches!(
            parse_event(slice8(&buf)),
            Event::Data(body) if body[..4] == (c::umac_data_commands::CMD_RX_BUFF as u32).to_le_bytes()
        ));
    }
}
