#![no_std]
#![deny(unused_must_use)]
#![allow(async_fn_in_trait)]

use core::mem::{align_of, size_of, zeroed};
use core::slice;

use align_data::{include_aligned, Align16};
use defmt::{assert, panic, todo, unwrap, *};
use embassy_futures::select::{select, Either};
use embassy_net_driver_channel as ch;
use embassy_sync::blocking_mutex::raw::NoopRawMutex;
use embassy_sync::channel::Channel;
use embassy_time::{with_timeout, Duration, Instant, Timer};
use embedded_hal::digital::{InputPin, OutputPin};
use embedded_hal::spi::Operation;
use embedded_hal_async::digital::Wait;
use embedded_hal_async::spi::SpiDevice;
use regions::*;

#[allow(unused)]
#[allow(non_camel_case_types)]
#[allow(non_snake_case)]
#[allow(clippy::all)] // generated by bindgen
mod c {
    include!("../fw/bindings.rs");
    pub const RPU_MCU_CORE_INDIRECT_BASE: u32 = 0xC0000000;
    pub const RX_BUF_HEADROOM: u32 = 4;
}

const MTU: usize = 1514;

/// How long the RPU gets to answer the init command and interface changes.
const EVENT_TIMEOUT: Duration = Duration::from_secs(5);
/// A scan covers every 2.4 GHz and 5 GHz channel, which takes a few seconds.
const SCAN_TIMEOUT: Duration = Duration::from_secs(30);
/// The RPU pulses HOST_IRQ once per event. Poll this often as well, in case an edge is missed.
const IRQ_POLL_PERIOD: Duration = Duration::from_millis(50);
/// Scan results buffered between the runner and a [`Scanner`].
const SCAN_RESULTS_DEPTH: usize = 32;

enum Request {
    Scan,
}

enum ScanEvent {
    Bss(BssInfo),
    Done,
    Aborted,
}

struct Shared {
    requests: Channel<NoopRawMutex, Request, 1>,
    scan_results: Channel<NoopRawMutex, ScanEvent, SCAN_RESULTS_DEPTH>,
}

pub struct State {
    shared: Shared,
    ch: ch::State<MTU, 4, 4>,
}

impl State {
    pub fn new() -> Self {
        Self {
            ch: ch::State::new(),
            shared: Shared {
                requests: Channel::new(),
                scan_results: Channel::new(),
            },
        }
    }
}

impl Default for State {
    fn default() -> Self {
        Self::new()
    }
}

pub type NetDriver<'a> = ch::Device<'a, MTU>;

/// Board settings, which the nRF Connect SDK takes from the devicetree and Kconfig.
#[derive(Clone, Copy, Debug, defmt::Format)]
pub struct Config {
    /// The highest TX power the board may use. The RPU uses the lower of this and the chip's own
    /// limits.
    pub max_tx_power: TxPowerCeiling,
    /// ISO 3166-1 alpha-2 country code of the regulatory domain, `*b"00"` for the world domain.
    pub country_code: [u8; 2],
}

/// Highest TX power per band and modulation, in dBm (the devicetree's `wifi-max-tx-pwr-*`).
#[derive(Clone, Copy, Debug, defmt::Format)]
pub struct TxPowerCeiling {
    pub dsss_2g: u8,
    pub mcs0_2g: u8,
    pub mcs7_2g: u8,
    pub mcs0_5g_low: u8,
    pub mcs7_5g_low: u8,
    pub mcs0_5g_mid: u8,
    pub mcs7_5g_mid: u8,
    pub mcs0_5g_high: u8,
    pub mcs7_5g_high: u8,
}

pub async fn new<'a, BUS, IN, OUT>(
    state: &'a mut State,
    bus: BUS,
    bucken: OUT,
    iovdd_ctl: OUT,
    host_irq: IN,
    config: Config,
) -> (NetDriver<'a>, Control<'a>, Runner<'a, BUS, IN, OUT>)
where
    BUS: Bus,
    IN: InputPin + Wait,
    OUT: OutputPin,
{
    let (ch_runner, device) = ch::new(&mut state.ch, ch::driver::HardwareAddress::Ethernet([0; 6]));
    let state_ch = ch_runner.state_runner();

    let mut runner = Runner {
        ch: ch_runner,
        state_ch,
        shared: &state.shared,
        bus,
        bucken,
        iovdd_ctl,
        host_irq,
        rpu_info: None,
        num_commands: c::RPU_CMD_START_MAGIC,
        irq_pending_ack: false,
        scan_deadline: None,
    };
    runner.init(&config).await;

    let control = Control {
        shared: &state.shared,
        state_ch,
    };

    (device, control, runner)
}

pub struct Control<'a> {
    shared: &'a Shared,
    #[allow(unused)]
    state_ch: ch::StateRunner<'a>,
}

impl<'a> Control<'a> {
    /// Starts an active scan of every channel. The results arrive through the returned [`Scanner`].
    pub async fn scan(&mut self) -> Scanner<'_> {
        self.shared.scan_results.clear();
        self.shared.requests.send(Request::Scan).await;
        Scanner {
            shared: self.shared,
            done: false,
        }
    }
}

/// The results of one scan, as the RPU reports them.
pub struct Scanner<'a> {
    shared: &'a Shared,
    done: bool,
}

impl Scanner<'_> {
    /// Returns the next BSS, or `None` once the scan has completed, been aborted or timed out.
    pub async fn next(&mut self) -> Option<BssInfo> {
        if self.done {
            return None;
        }
        let event = match with_timeout(SCAN_TIMEOUT, self.shared.scan_results.receive()).await {
            Ok(event) => event,
            Err(_) => {
                warn!("scan timed out");
                ScanEvent::Aborted
            }
        };
        match event {
            ScanEvent::Bss(bss) => Some(bss),
            ScanEvent::Done => {
                self.done = true;
                None
            }
            ScanEvent::Aborted => {
                warn!("scan aborted");
                self.done = true;
                None
            }
        }
    }
}

/// Frequency band of a BSS.
#[derive(Clone, Copy, Debug, PartialEq, Eq, defmt::Format)]
pub enum Band {
    Band2_4GHz,
    Band5GHz,
    Unknown(u32),
}

/// Security of a BSS, as the RPU classifies it.
#[derive(Clone, Copy, Debug, PartialEq, Eq, defmt::Format)]
pub enum Security {
    Open,
    Wep,
    Wpa,
    Wpa2,
    Wpa2Sha256,
    Wpa3,
    Wapi,
    Eap,
    Unknown(u32),
}

/// One scan result.
#[derive(Clone, Debug, defmt::Format)]
pub struct BssInfo {
    ssid: [u8; 32],
    ssid_len: u8,
    pub bssid: [u8; 6],
    pub band: Band,
    pub channel: u32,
    /// Signal strength in dBm, when the RPU reports it in mBm.
    pub rssi: Option<i32>,
    pub security: Security,
    pub beacon_interval: u16,
}

impl BssInfo {
    pub fn ssid(&self) -> &[u8] {
        &self.ssid[..self.ssid_len as usize]
    }

    fn from_display_result(r: &c::umac_display_results) -> Self {
        let ssid_len = r.ssid.ssid_len.min(32);
        let band = r.nwk_band as u32;
        let security = r.security_type as u32;
        let signal_type = r.signal.signal_type;
        let mbm = unsafe { r.signal.signal.mbm_signal } as i32;
        Self {
            ssid: r.ssid.ssid,
            ssid_len,
            bssid: r.mac_addr,
            band: match c::band::try_from(band) {
                Ok(c::band::BAND_2GHZ) => Band::Band2_4GHz,
                Ok(c::band::BAND_5GHZ) => Band::Band5GHz,
                _ => Band::Unknown(band),
            },
            channel: r.nwk_channel,
            rssi: (signal_type == c::SIGNAL_TYPE_MBM).then_some(mbm / 100),
            security: match c::security_type::try_from(security) {
                Ok(c::security_type::OPEN) => Security::Open,
                Ok(c::security_type::WEP) => Security::Wep,
                Ok(c::security_type::WPA) => Security::Wpa,
                Ok(c::security_type::WPA2) => Security::Wpa2,
                Ok(c::security_type::WPA2_256) => Security::Wpa2Sha256,
                Ok(
                    c::security_type::WPA3_HNP
                    | c::security_type::WPA3_H2E
                    | c::security_type::WPA3_AUTO
                    | c::security_type::WPA3_FT_SAE,
                ) => Security::Wpa3,
                Ok(c::security_type::WAPI) => Security::Wapi,
                Ok(c::security_type::EAP) => Security::Eap,
                // The other EAP and SHA-384 variants, which the SDK does not map either.
                _ => Security::Unknown(security),
            },
            beacon_interval: r.beacon_interval,
        }
    }
}

trait Command {
    const MESSAGE_TYPE: c::host_rpu_msg_type;
    fn fill(&mut self);
}

macro_rules! impl_cmd {
    (sys, $cmd:path, $num:expr) => {
        impl Command for $cmd {
            const MESSAGE_TYPE: c::host_rpu_msg_type = c::host_rpu_msg_type::HOST_RPU_MSG_TYPE_SYSTEM;
            fn fill(&mut self) {
                self.sys_head = c::sys_head {
                    cmd_event: $num as _,
                    len: size_of::<Self>() as _,
                };
            }
        }
    };
    (umac, $cmd:path, $num:expr) => {
        impl Command for $cmd {
            const MESSAGE_TYPE: c::host_rpu_msg_type = c::host_rpu_msg_type::HOST_RPU_MSG_TYPE_UMAC;
            fn fill(&mut self) {
                // Every UMAC command addresses the default interface, wdev 0.
                self.umac_hdr = c::umac_hdr {
                    cmd_evnt: $num as _,
                    ids: c::index_ids {
                        valid_fields: c::INDEX_IDS_WDEV_ID_VALID,
                        wdev_id: 0,
                        ..unsafe { zeroed() }
                    },
                    ..unsafe { zeroed() }
                };
            }
        }
    };
}

impl_cmd!(sys, c::cmd_sys_init, c::sys_commands::CMD_INIT);
impl_cmd!(
    umac,
    c::umac_cmd_change_macaddr,
    c::umac_commands::UMAC_CMD_CHANGE_MACADDR
);
impl_cmd!(umac, c::umac_cmd_chg_vif_state, c::umac_commands::UMAC_CMD_SET_IFFLAGS);
impl_cmd!(umac, c::umac_cmd_scan, c::umac_commands::UMAC_CMD_TRIGGER_SCAN);
impl_cmd!(
    umac,
    c::umac_cmd_get_scan_results,
    c::umac_commands::UMAC_CMD_GET_SCAN_RESULTS
);

fn sliceit<T>(t: &T) -> &[u8] {
    unsafe { slice::from_raw_parts(t as *const _ as _, size_of::<T>()) }
}

fn unsliceit2<T>(t: &[u8]) -> (&T, &[u8]) {
    assert!(t.len() > size_of::<T>());
    assert!((t.as_ptr() as usize).is_multiple_of(align_of::<T>()));
    (unsafe { &*(t.as_ptr() as *const T) }, &t[size_of::<T>()..])
}

fn unsliceit<T>(t: &[u8]) -> &T {
    unsliceit2(t).0
}

fn slice8(x: &[u32]) -> &[u8] {
    let len = x.len() * 4;
    unsafe { slice::from_raw_parts(x.as_ptr() as _, len) }
}

fn slice8_mut(x: &mut [u32]) -> &mut [u8] {
    let len = x.len() * 4;
    unsafe { slice::from_raw_parts_mut(x.as_mut_ptr() as _, len) }
}

#[derive(Copy, Clone, Debug, defmt::Format)]
struct MemoryRegion {
    start: u32,
    end: u32,

    /// Number of dummy 32bit words
    latency: u32,

    rpu_mem_start: u32,
    rpu_mem_end: u32,
    processor_restriction: Option<Processor>,
}

#[rustfmt::skip]
pub(crate) mod regions {
    use super::*;
	pub(crate) const SYSBUS       : &MemoryRegion = &MemoryRegion { start: 0x000000, end: 0x008FFF, latency: 1, rpu_mem_start: 0xA4000000, rpu_mem_end: 0xA4FFFFFF, processor_restriction: None };
	pub(crate) const EXT_SYS_BUS  : &MemoryRegion = &MemoryRegion { start: 0x009000, end: 0x03FFFF, latency: 2, rpu_mem_start: 0,          rpu_mem_end: 0,          processor_restriction: None };
	pub(crate) const PBUS         : &MemoryRegion = &MemoryRegion { start: 0x040000, end: 0x07FFFF, latency: 1, rpu_mem_start: 0xA5000000, rpu_mem_end: 0xA5FFFFFF, processor_restriction: None };
	pub(crate) const PKTRAM       : &MemoryRegion = &MemoryRegion { start: 0x0C0000, end: 0x0F0FFF, latency: 0, rpu_mem_start: 0xB0000000, rpu_mem_end: 0xB0FFFFFF, processor_restriction: None };
	pub(crate) const GRAM         : &MemoryRegion = &MemoryRegion { start: 0x080000, end: 0x092000, latency: 2, rpu_mem_start: 0xB7000000, rpu_mem_end: 0xB7FFFFFF, processor_restriction: None };
	pub(crate) const LMAC_ROM     : &MemoryRegion = &MemoryRegion { start: 0x100000, end: 0x134000, latency: 1, rpu_mem_start: 0x80000000, rpu_mem_end: 0x80033FFF, processor_restriction: Some(Processor::Lmac) }; // ROM
	pub(crate) const LMAC_RET_RAM : &MemoryRegion = &MemoryRegion { start: 0x140000, end: 0x14C000, latency: 1, rpu_mem_start: 0x80040000, rpu_mem_end: 0x8004BFFF, processor_restriction: Some(Processor::Lmac) }; // retained RAM
	pub(crate) const LMAC_SRC_RAM : &MemoryRegion = &MemoryRegion { start: 0x180000, end: 0x190000, latency: 1, rpu_mem_start: 0x80080000, rpu_mem_end: 0x8008FFFF, processor_restriction: Some(Processor::Lmac) }; // scratch RAM
	pub(crate) const UMAC_ROM     : &MemoryRegion = &MemoryRegion { start: 0x200000, end: 0x261800, latency: 1, rpu_mem_start: 0x80000000, rpu_mem_end: 0x800617FF, processor_restriction: Some(Processor::Umac) }; // ROM
	pub(crate) const UMAC_RET_RAM : &MemoryRegion = &MemoryRegion { start: 0x280000, end: 0x2A4000, latency: 1, rpu_mem_start: 0x80080000, rpu_mem_end: 0x800A3FFF, processor_restriction: Some(Processor::Umac) }; // retained RAM
	pub(crate) const UMAC_SRC_RAM : &MemoryRegion = &MemoryRegion { start: 0x300000, end: 0x338000, latency: 1, rpu_mem_start: 0x80100000, rpu_mem_end: 0x80137FFF, processor_restriction: Some(Processor::Umac) }; // scratch RAM

    pub(crate) const REGIONS: [&MemoryRegion; 11] = [
        SYSBUS, EXT_SYS_BUS, PBUS, PKTRAM, GRAM, LMAC_ROM, LMAC_RET_RAM, LMAC_SRC_RAM, UMAC_ROM, UMAC_RET_RAM, UMAC_SRC_RAM
    ];

    #[doc(alias = "pal_rpu_addr_offset_get")]
    pub(crate) fn remap_global_addr_to_region_and_offset(rpu_addr: u32, processor: Option<Processor>) -> (&'static MemoryRegion, u32) {
        defmt::unwrap!(
            REGIONS
                .into_iter()
                .filter(|region| region.processor_restriction.is_none() || region.processor_restriction == processor)
                .find(|region| rpu_addr >= region.rpu_mem_start && rpu_addr <= region.rpu_mem_end)
                .map(|region| (region, rpu_addr - region.rpu_mem_start))
        )
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, defmt::Format)]
pub(crate) enum Processor {
    Lmac,
    Umac,
}

/// The nRF70 firmware, in the nRF Connect SDK's `nrf70.bin` format: a header, then the UMAC and
/// LMAC patches. `gen.py` takes it from the SDK release that `fw/bindings.rs` comes from.
static FIRMWARE: &[u8] = include_aligned!(Align16, "../fw/nrf70.bin");

/// The four patch images of an `nrf70.bin`.
struct Firmware<'a> {
    umac_pri: &'a [u8],
    umac_sec: &'a [u8],
    lmac_pri: &'a [u8],
    lmac_sec: &'a [u8],
}

/// Splits an `nrf70.bin` into its images, after checking that it is a system (station) mode
/// firmware of the version the bindings come from (NCS `nrf_wifi_fmac_fw_parse`).
fn parse_firmware(fw: &[u8]) -> Firmware<'_> {
    let word = |offset: usize| u32::from_le_bytes(unwrap!(fw[offset..offset + 4].try_into()));

    assert!(word(0) == c::PATCH_SIGNATURE, "not an nRF70 firmware file");
    assert!(word(4) == c::PATCH_NUM_IMAGES, "unexpected number of firmware images");
    let version = word(8);
    let expected = c::RPU_FAMILY << 24 | c::RPU_MAJOR_VERSION << 16 | c::RPU_MINOR_VERSION << 8 | c::RPU_PATCH_VERSION;
    assert!(
        version == expected,
        "firmware version {:08x} does not match the bindings ({:08x})",
        version,
        expected
    );
    let system_mode = c::nrf70_feature_flags::NRF70_FEAT_SYSTEM_MODE as u32;
    assert!(word(12) & system_mode != 0, "not a system mode firmware");

    // Each image is a type and a length, then the data, in `nrf70_image_ids` order. The data is
    // not word aligned: one image has an odd length.
    let mut images = [&fw[..0]; 4];
    let mut offset = size_of::<c::nrf70_fw_image_info>();
    for image in &mut images {
        let len = word(offset + 4) as usize;
        let start = offset + size_of::<c::nrf70_fw_image>();
        *image = &fw[start..start + len];
        offset = start + len;
    }
    let [umac_pri, umac_sec, lmac_pri, lmac_sec] = images;
    Firmware {
        umac_pri,
        umac_sec,
        lmac_pri,
        lmac_sec,
    }
}

const SR0_WRITE_IN_PROGRESS: u8 = 0x01;

const SR1_RPU_AWAKE: u8 = 0x02;
const SR1_RPU_READY: u8 = 0x04;

const SR2_RPU_WAKEUP_REQ: u8 = 0x01;

const MAX_EVENT_POOL_LEN: usize = 1000;

/// Largest command the RPU takes in one buffer; longer ones are sent in fragments.
const MAX_CMD_SIZE: usize = c::MAX_UMAC_CMD_SIZE as usize;

/// How long a processor gets to write its boot signature (NCS `MCU_FW_BOOT_TIMEOUT_MS`).
const FW_BOOT_TIMEOUT: Duration = Duration::from_secs(1);

// ========= RF parameters

const _: () = core::assert!(size_of::<c::phy_rf_params>() == c::RF_PARAMS_SIZE as usize);

/// What the UMAC reads out of the chip's OTP at boot.
struct Otp {
    info: c::host_rpu_umac_info,
    /// One "not programmed" bit per field.
    flags: u32,
    /// Version of the production test program that wrote the calibration.
    ft_prog_ver: u32,
    /// `QFN_PACKAGE_INFO` or `CSP_PACKAGE_INFO`, or 0xFFFFFFFF if not programmed.
    package_info: u32,
}

const fn hex_nibble(c: u8) -> u8 {
    match c {
        b'0'..=b'9' => c - b'0',
        b'A'..=b'F' => c - b'A' + 10,
        b'a'..=b'f' => c - b'a' + 10,
        _ => core::panic!("invalid hex digit"),
    }
}

/// A byte of `phy_rf_params_common.h`, which writes signed values as unsigned hex.
const fn byte(value: u32) -> i8 {
    value as u8 as i8
}

/// Builds the RF parameters as the nRF Connect SDK does (`nrf_wifi_sys_fmac_rf_params_get`): the
/// defaults for the chip's package, the crystal calibration from OTP, and TX power ceilings that
/// are the lower of the board's and the package's, less a backoff for the chip's test program.
fn rf_params(otp: &Otp, board: &TxPowerCeiling) -> c::phy_rf_params {
    let mut p: c::phy_rf_params = unsafe { zeroed() };

    p.pd_adjust_val = c::pd_adst_val {
        pd_adjt_lb_chan: byte(c::PD_ADJUST_VAL),
        pd_adjt_hb_low_chan: byte(c::PD_ADJUST_VAL),
        pd_adjt_hb_mid_chan: byte(c::PD_ADJUST_VAL),
        pd_adjt_hb_high_chan: byte(c::PD_ADJUST_VAL),
    };
    p.rx_gain_offset = c::rx_gain_offset {
        rx_gain_lb_chan: byte(c::CTRL_PWR_OPTIMIZATIONS),
        rx_gain_hb_low_chan: byte(c::RX_GAIN_OFFSET_HB_LOW_CHAN),
        rx_gain_hb_mid_chan: byte(c::RX_GAIN_OFFSET_HB_MID_CHAN),
        rx_gain_hb_high_chan: byte(c::RX_GAIN_OFFSET_HB_HIGH_CHAN),
    };

    // A chip without package information in OTP is taken to be a QFN.
    if otp.package_info == c::CSP_PACKAGE_INFO {
        p.xo_offset.xo_freq_offset = c::CSP_XO_VAL as u8;
        p.syst_tx_pwr_offset = c::tx_pwr_systm_offset {
            syst_off_lb_chan: byte(c::CSP_SYSTEM_OFFSET_LB),
            syst_off_hb_low_chan: byte(c::CSP_SYSTEM_OFFSET_HB_CHAN_LOW),
            syst_off_hb_mid_chan: byte(c::CSP_SYSTEM_OFFSET_HB_CHAN_MID),
            syst_off_hb_high_chan: byte(c::CSP_SYSTEM_OFFSET_HB_CHAN_HIGH),
        };
        p.max_pwr_ceil = c::tx_pwr_ceil {
            max_dsss_pwr: byte(c::CSP_MAX_TX_PWR_DSSS),
            max_lb_mcs7_pwr: byte(c::CSP_MAX_TX_PWR_LB_MCS7),
            max_lb_mcs0_pwr: byte(c::CSP_MAX_TX_PWR_LB_MCS0),
            max_hb_low_chan_mcs7_pwr: byte(c::CSP_MAX_TX_PWR_HB_LOW_CHAN_MCS7),
            max_hb_mid_chan_mcs7_pwr: byte(c::CSP_MAX_TX_PWR_HB_MID_CHAN_MCS7),
            max_hb_high_chan_mcs7_pwr: byte(c::CSP_MAX_TX_PWR_HB_HIGH_CHAN_MCS7),
            max_hb_low_chan_mcs0_pwr: byte(c::CSP_MAX_TX_PWR_HB_LOW_CHAN_MCS0),
            max_hb_mid_chan_mcs0_pwr: byte(c::CSP_MAX_TX_PWR_HB_MID_CHAN_MCS0),
            max_hb_high_chan_mcs0_pwr: byte(c::CSP_MAX_TX_PWR_HB_HIGH_CHAN_MCS0),
        };
        p.temp_volt_backoff = c::temp_volt_depend_params {
            max_chip_temp: byte(c::CSP_MAX_CHIP_TEMP),
            min_chip_temp: byte(c::CSP_MIN_CHIP_TEMP),
            lb_max_pwr_bkf_hi_temp: byte(c::CSP_LB_MAX_PWR_BKF_HI_TEMP),
            lb_max_pwr_bkf_low_temp: byte(c::CSP_LB_MAX_PWR_BKF_LOW_TEMP),
            hb_max_pwr_bkf_hi_temp: byte(c::CSP_HB_MAX_PWR_BKF_HI_TEMP),
            hb_max_pwr_bkf_low_temp: byte(c::CSP_HB_MAX_PWR_BKF_LOW_TEMP),
            lb_vbt_lt_vlow: byte(c::CSP_LB_VBT_LT_VLOW),
            hb_vbt_lt_vlow: byte(c::CSP_HB_VBT_LT_VLOW),
            lb_vbt_lt_low: byte(c::CSP_LB_VBT_LT_LOW),
            hb_vbt_lt_low: byte(c::CSP_HB_VBT_LT_LOW),
            reserved: [0; 4],
        };
    } else {
        p.xo_offset.xo_freq_offset = c::QFN_XO_VAL as u8;
        p.syst_tx_pwr_offset = c::tx_pwr_systm_offset {
            syst_off_lb_chan: byte(c::QFN_SYSTEM_OFFSET_LB),
            syst_off_hb_low_chan: byte(c::QFN_SYSTEM_OFFSET_HB_CHAN_LOW),
            syst_off_hb_mid_chan: byte(c::QFN_SYSTEM_OFFSET_HB_CHAN_MID),
            syst_off_hb_high_chan: byte(c::QFN_SYSTEM_OFFSET_HB_CHAN_HIGH),
        };
        p.max_pwr_ceil = c::tx_pwr_ceil {
            max_dsss_pwr: byte(c::QFN_MAX_TX_PWR_DSSS),
            max_lb_mcs7_pwr: byte(c::QFN_MAX_TX_PWR_LB_MCS7),
            max_lb_mcs0_pwr: byte(c::QFN_MAX_TX_PWR_LB_MCS0),
            max_hb_low_chan_mcs7_pwr: byte(c::QFN_MAX_TX_PWR_HB_LOW_CHAN_MCS7),
            max_hb_mid_chan_mcs7_pwr: byte(c::QFN_MAX_TX_PWR_HB_MID_CHAN_MCS7),
            max_hb_high_chan_mcs7_pwr: byte(c::QFN_MAX_TX_PWR_HB_HIGH_CHAN_MCS7),
            max_hb_low_chan_mcs0_pwr: byte(c::QFN_MAX_TX_PWR_HB_LOW_CHAN_MCS0),
            max_hb_mid_chan_mcs0_pwr: byte(c::QFN_MAX_TX_PWR_HB_MID_CHAN_MCS0),
            max_hb_high_chan_mcs0_pwr: byte(c::QFN_MAX_TX_PWR_HB_HIGH_CHAN_MCS0),
        };
        p.temp_volt_backoff = c::temp_volt_depend_params {
            max_chip_temp: byte(c::QFN_MAX_CHIP_TEMP),
            min_chip_temp: byte(c::QFN_MIN_CHIP_TEMP),
            lb_max_pwr_bkf_hi_temp: byte(c::QFN_LB_MAX_PWR_BKF_HI_TEMP),
            lb_max_pwr_bkf_low_temp: byte(c::QFN_LB_MAX_PWR_BKF_LOW_TEMP),
            hb_max_pwr_bkf_hi_temp: byte(c::QFN_HB_MAX_PWR_BKF_HI_TEMP),
            hb_max_pwr_bkf_low_temp: byte(c::QFN_HB_MAX_PWR_BKF_LOW_TEMP),
            lb_vbt_lt_vlow: byte(c::QFN_LB_VBT_LT_VLOW),
            hb_vbt_lt_vlow: byte(c::QFN_HB_VBT_LT_VLOW),
            lb_vbt_lt_low: byte(c::QFN_LB_VBT_LT_LOW),
            hb_vbt_lt_low: byte(c::QFN_HB_VBT_LT_LOW),
            reserved: [0; 4],
        };
    }

    // The PHY defaults. The band edge backoffs, antenna gains and PCB losses that follow them stay
    // 0, the SDK's Kconfig defaults.
    let hex = &c::SYS_DEF_RF_PARAMS[..c::SYS_DEF_RF_PARAMS.len() - 1];
    for (dst, [high, low]) in p.phy_params.iter_mut().zip(hex.as_chunks::<2>().0) {
        *dst = hex_nibble(*high) << 4 | hex_nibble(*low);
    }

    if otp.flags & !(c::CALIB_XO_FLAG_MASK as u32) == 0 {
        let calib = otp.info.calib;
        let offset = c::OTP_OFF_CALIB_XO as usize;
        p.xo_offset.xo_freq_offset = calib[offset / 4].to_le_bytes()[offset % 4];
    }

    let backoffs = match c::ft_prog_ver::try_from((otp.ft_prog_ver & c::FT_PROG_VER_MASK) >> 16) {
        Ok(c::ft_prog_ver::FT_PROG_VER1) => [
            c::FT_PROG_VER1_2G_DSSS_TXCEIL_BKOFF,
            c::FT_PROG_VER1_2G_OFDM_TXCEIL_BKOFF,
            c::FT_PROG_VER1_5G_LOW_OFDM_TXCEIL_BKOFF,
            c::FT_PROG_VER1_5G_MID_OFDM_TXCEIL_BKOFF,
            c::FT_PROG_VER1_5G_HIGH_OFDM_TXCEIL_BKOFF,
        ],
        Ok(c::ft_prog_ver::FT_PROG_VER2) => [
            c::FT_PROG_VER2_2G_DSSS_TXCEIL_BKOFF,
            c::FT_PROG_VER2_2G_OFDM_TXCEIL_BKOFF,
            c::FT_PROG_VER2_5G_LOW_OFDM_TXCEIL_BKOFF,
            c::FT_PROG_VER2_5G_MID_OFDM_TXCEIL_BKOFF,
            c::FT_PROG_VER2_5G_HIGH_OFDM_TXCEIL_BKOFF,
        ],
        Ok(c::ft_prog_ver::FT_PROG_VER3) => [
            c::FT_PROG_VER3_2G_DSSS_TXCEIL_BKOFF,
            c::FT_PROG_VER3_2G_OFDM_TXCEIL_BKOFF,
            c::FT_PROG_VER3_5G_LOW_OFDM_TXCEIL_BKOFF,
            c::FT_PROG_VER3_5G_MID_OFDM_TXCEIL_BKOFF,
            c::FT_PROG_VER3_5G_HIGH_OFDM_TXCEIL_BKOFF,
        ],
        Err(_) => [0; 5],
    };
    let [dsss_2g, ofdm_2g, ofdm_5g_low, ofdm_5g_mid, ofdm_5g_high] = backoffs.map(|b| b as i32);

    // Both ceilings are in quarter dB.
    let ceiling = |board_dbm: u8, package: i8, backoff: i32| -> i8 {
        ((board_dbm as i32 * 4).min(package as i32) - backoff) as i8
    };
    let pkg = p.max_pwr_ceil;
    p.max_pwr_ceil = c::tx_pwr_ceil {
        max_dsss_pwr: ceiling(board.dsss_2g, pkg.max_dsss_pwr, dsss_2g),
        max_lb_mcs7_pwr: ceiling(board.mcs7_2g, pkg.max_lb_mcs7_pwr, ofdm_2g),
        max_lb_mcs0_pwr: ceiling(board.mcs0_2g, pkg.max_lb_mcs0_pwr, ofdm_2g),
        max_hb_low_chan_mcs7_pwr: ceiling(board.mcs7_5g_low, pkg.max_hb_low_chan_mcs7_pwr, ofdm_5g_low),
        max_hb_mid_chan_mcs7_pwr: ceiling(board.mcs7_5g_mid, pkg.max_hb_mid_chan_mcs7_pwr, ofdm_5g_mid),
        max_hb_high_chan_mcs7_pwr: ceiling(board.mcs7_5g_high, pkg.max_hb_high_chan_mcs7_pwr, ofdm_5g_high),
        max_hb_low_chan_mcs0_pwr: ceiling(board.mcs0_5g_low, pkg.max_hb_low_chan_mcs0_pwr, ofdm_5g_low),
        max_hb_mid_chan_mcs0_pwr: ceiling(board.mcs0_5g_mid, pkg.max_hb_mid_chan_mcs0_pwr, ofdm_5g_mid),
        max_hb_high_chan_mcs0_pwr: ceiling(board.mcs0_5g_high, pkg.max_hb_high_chan_mcs0_pwr, ofdm_5g_high),
    };

    p
}

/// The MAC address programmed in OTP (`MAC0`), if it is a valid unicast address.
fn otp_mac_address(otp: &c::host_rpu_umac_info) -> Option<[u8; 6]> {
    let words = otp.mac_address0;
    let mut bytes = [0u8; 8];
    bytes[..4].copy_from_slice(&words[0].to_le_bytes());
    bytes[4..].copy_from_slice(&words[1].to_le_bytes());
    let mac: [u8; 6] = unwrap!(bytes[..6].try_into());
    let unset = mac == [0; 6] || mac == [0xFF; 6];
    let multicast = mac[0] & 0x01 != 0;
    (!unset && !multicast).then_some(mac)
}

/// Locally administered address used when the OTP holds none.
const FALLBACK_MAC_ADDRESS: [u8; 6] = [0x02, 0x70, 0x02, 0x00, 0x00, 0x01];

// ========= config
/*
pktram: 0xB0000000 - 0xB0030FFF -- 196kb
usable for mcu-rpu comms: 0xB0005000 - 0xB0030FFF -- 176kb

First we allocate N tx buffers, which consist of
- Header of 52 bytes
- Data of N bytes

Then we allocate rx buffers.
- 3 queues of
  - N buffers each, which consist of
    - Header of 4 bytes
    - Data of N bytes (default 1600)

Each RX buffer has a "descriptor ID" which is assigned across all queues starting from 0
- queue 0 is descriptors 0..N-1
- queue 1 is descriptors N..2N-1
- queue 2 is descriptors 2N..3N-1
*/

// configurable by user
const MAX_TX_TOKENS: usize = 10;
const MAX_TX_AGGREGATION: usize = 6;
const TX_MAX_DATA_SIZE: usize = 1600;
const RX_MAX_DATA_SIZE: usize = 1600;
const RX_BUFS_PER_QUEUE: usize = 16;

// fixed

const TX_BUFS: usize = MAX_TX_TOKENS * MAX_TX_AGGREGATION;
const TX_BUF_SIZE: usize = c::TX_BUF_HEADROOM as usize + TX_MAX_DATA_SIZE;
const TX_TOTAL_SIZE: usize = TX_BUFS * TX_BUF_SIZE;

const RX_BUFS: usize = RX_BUFS_PER_QUEUE * c::MAX_NUM_OF_RX_QUEUES as usize;
const RX_BUF_SIZE: usize = c::RX_BUF_HEADROOM as usize + RX_MAX_DATA_SIZE;
const RX_TOTAL_SIZE: usize = RX_BUFS * RX_BUF_SIZE;

const _: () = {
    use core::assert;
    assert!(MAX_TX_TOKENS >= 1, "At least one TX token is required");
    assert!(MAX_TX_AGGREGATION <= 16, "Max TX aggregation is 16");
    assert!(RX_BUFS_PER_QUEUE >= 1, "At least one RX buffer per queue is required");
    assert!(
        (TX_TOTAL_SIZE + RX_TOTAL_SIZE) as u32 <= c::RPU_PKTRAM_SIZE,
        "Packet RAM overflow"
    );
};

/// An event from the RPU, as far as the runner needs to tell them apart.
enum Event<'b> {
    /// A system event, by `sys_events` number.
    Sys(u32),
    /// A UMAC event, by `umac_events` number, with the whole message (which starts with its
    /// `umac_hdr`).
    Umac(u32, &'b [u8]),
    /// A data path event, by `umac_data_commands` number, with the whole message (which starts
    /// with its `umac_head`).
    Data(u32, &'b [u8]),
    /// Any other message type.
    Other(u32),
}

fn parse_event(buf: &[u8]) -> Event<'_> {
    let (msg, body) = unsliceit2::<c::host_rpu_msg>(buf);
    let msg_type = msg.type_ as u32;
    match c::host_rpu_msg_type::try_from(msg_type) {
        Ok(c::host_rpu_msg_type::HOST_RPU_MSG_TYPE_SYSTEM) => Event::Sys(unsliceit::<c::sys_head>(body).cmd_event),
        Ok(c::host_rpu_msg_type::HOST_RPU_MSG_TYPE_UMAC) => Event::Umac(unsliceit::<c::umac_hdr>(body).cmd_evnt, body),
        Ok(c::host_rpu_msg_type::HOST_RPU_MSG_TYPE_DATA) => Event::Data(unsliceit::<c::umac_head>(body).cmd, body),
        _ => Event::Other(msg_type),
    }
}

pub struct Runner<'a, BUS: Bus, IN: InputPin + Wait, OUT: OutputPin> {
    #[allow(unused)]
    ch: ch::Runner<'a, MTU>,
    state_ch: ch::StateRunner<'a>,
    shared: &'a Shared,

    bus: BUS,
    bucken: OUT,
    iovdd_ctl: OUT,
    host_irq: IN,

    rpu_info: Option<RpuInfo>,

    num_commands: u32,

    /// Set when events have been read since the last interrupt acknowledgement.
    irq_pending_ack: bool,

    /// Set while a display scan is running, so a lost one does not block the next.
    scan_deadline: Option<Instant>,
}

impl<'a, BUS: Bus, IN: InputPin + Wait, OUT: OutputPin> Runner<'a, BUS, IN, OUT> {
    async fn init(&mut self, config: &Config) {
        info!("power on...");
        Timer::after(Duration::from_millis(10)).await;
        self.bucken.set_high().unwrap();
        Timer::after(Duration::from_millis(10)).await;
        self.iovdd_ctl.set_high().unwrap();
        Timer::after(Duration::from_millis(10)).await;

        info!("wakeup...");
        self.rpu_wakeup().await;

        info!("enable clocks...");
        self.raw_write32(PBUS, 0x8C20, 0x0100).await;

        info!("enable interrupt...");
        // First enable the blockwise interrupt for the relevant block in the master register
        let mut val = self.raw_read32(SYSBUS, 0x400).await;
        val |= 1 << 17;
        self.raw_write32(SYSBUS, 0x400, val).await;

        // Now enable the relevant MCU interrupt line
        self.raw_write32(SYSBUS, 0x494, 1 << 31).await;

        // Based on 'nrf_wifi_fmac_fw_load'
        let fw = parse_firmware(FIRMWARE);

        info!("reset processors...");
        self.rpu_proc_reset(Processor::Lmac).await;
        self.rpu_proc_reset(Processor::Umac).await;

        info!("load firmware patches...");
        self.load_fw(Processor::Umac, c::RPU_MEM_UMAC_PATCH_BIMG, fw.umac_pri)
            .await;
        self.load_fw(Processor::Umac, c::RPU_MEM_UMAC_PATCH_BIN, fw.umac_sec)
            .await;
        self.load_fw(Processor::Lmac, c::RPU_MEM_LMAC_PATCH_BIMG, fw.lmac_pri)
            .await;
        self.load_fw(Processor::Lmac, c::RPU_MEM_LMAC_PATCH_BIN, fw.lmac_sec)
            .await;

        info!("booting LMAC...");
        self.rpu_proc_boot(Processor::Lmac).await;

        info!("booting UMAC...");
        self.rpu_proc_boot(Processor::Umac).await;

        let umac_ver = self.read32(c::RPU_MEM_UMAC_VER, None).await.to_be_bytes();
        let lmac_ver = self.read32(c::RPU_MEM_LMAC_VER, None).await.to_be_bytes();
        info!(
            "firmware booted: UMAC {}.{}.{}.{}, LMAC {}.{}.{}.{}",
            umac_ver[0], umac_ver[1], umac_ver[2], umac_ver[3], lmac_ver[0], lmac_ver[1], lmac_ver[2], lmac_ver[3]
        );

        info!("Initializing rpu info...");
        self.init_rpu_info().await;

        info!("Reading OTP...");
        let otp = self.read_otp().await;
        let rf_params = rf_params(&otp, &config.max_tx_power);
        let mac_addr = match otp_mac_address(&otp.info) {
            Some(mac) => mac,
            None => {
                warn!("no MAC address in OTP, using a locally administered one");
                FALLBACK_MAC_ADDRESS
            }
        };
        info!(
            "OTP flags {:08x}, package {:08x}, test program {:08x}, MAC address {:02x}",
            otp.flags, otp.package_info, otp.ft_prog_ver, mac_addr
        );

        info!("Enabling interrupts...");
        self.rpu_irq_enable().await;

        info!("Initializing TX...");
        self.init_tx().await;

        info!("Initializing RX...");
        self.init_rx().await;

        info!("Initializing umac...");
        self.init_umac(&rf_params, config).await;
        self.wait_for_event(
            "INIT_DONE",
            |event| matches!(event, Event::Sys(id) if *id == c::sys_events::EVENT_INIT_DONE as u32),
        )
        .await;
        info!("======== INIT DONE!! ==========");

        info!("Bringing the interface up...");
        self.set_mac_address(mac_addr).await;
        self.state_ch
            .set_hardware_address(ch::driver::HardwareAddress::Ethernet(mac_addr));
        self.set_interface_up().await;
    }

    pub async fn run(&mut self) -> ! {
        info!("running...");

        let mut buf = [0u32; MAX_EVENT_POOL_LEN / 4];

        loop {
            while self.rpu_event_next(&mut buf).await {
                self.handle_event(slice8(&buf)).await;
            }
            self.rpu_irq_service_end().await;

            let shared = self.shared;
            let irq = with_timeout(IRQ_POLL_PERIOD, self.host_irq.wait_for_rising_edge());
            match select(irq, shared.requests.receive()).await {
                Either::First(_) => {}
                Either::Second(request) => self.handle_request(request).await,
            }
        }
    }

    async fn handle_request(&mut self, request: Request) {
        match request {
            Request::Scan => {
                if let Some(deadline) = self.scan_deadline {
                    if Instant::now() < deadline {
                        warn!("scan already in progress");
                        self.push_scan_event(ScanEvent::Aborted);
                        return;
                    }
                }
                self.scan_deadline = Some(Instant::now() + SCAN_TIMEOUT);
                self.trigger_scan().await;
            }
        }
    }

    async fn handle_event(&mut self, buf: &[u8]) {
        match parse_event(buf) {
            Event::Sys(id) => match c::sys_events::try_from(id) {
                Ok(event) => debug!("sys event {}", event as u32),
                Err(_) => warn!("unknown sys event type {:08x}", id),
            },
            Event::Umac(id, body) => self.handle_umac_event(id, body).await,
            Event::Data(id, body) => self.handle_data_event(id, body).await,
            Event::Other(msg_type) => warn!("unknown event type {:08x}", msg_type),
        }
    }

    async fn handle_data_event(&mut self, id: u32, body: &[u8]) {
        match c::umac_data_commands::try_from(id) {
            Ok(c::umac_data_commands::CMD_RX_BUFF) => {
                let (rx, infos) = unsliceit2::<c::rx_buff>(body);
                let count = rx.rx_pkt_cnt as usize;
                for i in 0..count {
                    let info: &c::rx_buff_info = unsliceit(&infos[i * size_of::<c::rx_buff_info>()..]);
                    let desc_id = info.descriptor_id as usize;
                    if desc_id >= RX_BUFS {
                        warn!("RX event for invalid descriptor {}", desc_id);
                        continue;
                    }
                    // Frames are not passed to a network stack yet, so the buffer goes straight
                    // back to the RPU. Without this the RX pool drains.
                    self.rx_buf_post(desc_id).await;
                }
            }
            _ => debug!("unhandled data event {}", id),
        }
    }

    async fn handle_umac_event(&mut self, id: u32, body: &[u8]) {
        match c::umac_events::try_from(id) {
            Ok(c::umac_events::UMAC_EVENT_TRIGGER_SCAN_START) => debug!("scan started"),
            Ok(c::umac_events::UMAC_EVENT_SCAN_DONE) => {
                if self.scan_deadline.is_some() {
                    // A display scan hands its results over only when asked for them.
                    self.get_scan_results().await;
                }
            }
            Ok(c::umac_events::UMAC_EVENT_SCAN_ABORTED) => {
                self.scan_deadline = None;
                self.push_scan_event(ScanEvent::Aborted);
            }
            Ok(c::umac_events::UMAC_EVENT_SCAN_DISPLAY_RESULT) => {
                let event: &c::umac_event_new_scan_display_results = unsliceit(body);
                let count = (event.event_bss_count as usize).min(event.display_results.len());
                let seq = event.umac_hdr.seq;
                debug!("scan display results: seq {}, {} BSS", seq, count);
                for result in &event.display_results[..count] {
                    self.push_scan_event(ScanEvent::Bss(BssInfo::from_display_result(result)));
                }
                // The last batch of results has a zero sequence number.
                if seq == 0 {
                    self.scan_deadline = None;
                    self.push_scan_event(ScanEvent::Done);
                }
            }
            Ok(c::umac_events::UMAC_EVENT_IFFLAGS_STATUS) => {
                let status = unsliceit::<c::umac_event_vif_state>(body).status;
                debug!("interface flags status {}", status);
            }
            _ => debug!("unhandled UMAC event {}", id),
        }
    }

    fn push_scan_event(&mut self, event: ScanEvent) {
        if self.shared.scan_results.try_send(event).is_err() {
            warn!("scan result dropped, the scanner is not keeping up");
        }
    }

    /// Waits for an event that `matches` accepts, handling the others as usual.
    async fn wait_for_event(&mut self, what: &str, matches: impl Fn(&Event) -> bool) {
        let mut buf = [0u32; MAX_EVENT_POOL_LEN / 4];
        let found = with_timeout(EVENT_TIMEOUT, async {
            loop {
                self.next_event(&mut buf).await;
                if matches(&parse_event(slice8(&buf))) {
                    return;
                }
                self.handle_event(slice8(&buf)).await;
            }
        })
        .await;
        if found.is_err() {
            panic!("timed out waiting for {}", what);
        }
    }

    /// Reads the next event into `buf`, waiting for HOST_IRQ while the queue is empty.
    async fn next_event(&mut self, buf: &mut [u32]) {
        loop {
            if self.rpu_event_next(buf).await {
                return;
            }
            self.rpu_irq_service_end().await;
            let _ = with_timeout(IRQ_POLL_PERIOD, self.host_irq.wait_for_rising_edge()).await;
        }
    }

    /// Reads the next queued event into `buf`. Returns false if the queue is empty.
    async fn rpu_event_next(&mut self, buf: &mut [u32]) -> bool {
        let event_address = self
            .rpu_hpq_dequeue(self.rpu_info.as_ref().unwrap().hpqm_info.event_busy_queue)
            .await;

        match event_address {
            // No more events to read. Sometimes when low power mode is enabled
            // we see a wrong address, but it work after a while, so, add a
            // check for that.
            None | Some(0xAAAAAAAA) => false,
            Some(event_address) => {
                self.rpu_event_read(event_address, buf).await;
                self.irq_pending_ack = true;
                true
            }
        }
    }

    /// Ends an interrupt once the event queue is empty (NCS `hal_rpu_irq_process`): clears a
    /// watchdog interrupt, and acknowledges the interrupt if events were read.
    async fn rpu_irq_service_end(&mut self) {
        if self.rpu_irq_watchdog_check().await {
            debug!("RPU watchdog interrupt");
            self.rpu_irq_watchdog_ack().await;
        }
        if self.irq_pending_ack {
            self.rpu_irq_ack().await;
            self.irq_pending_ack = false;
        }
    }

    async fn rpu_irq_enable(&mut self) {
        // First enable the blockwise interrupt for the relevant block in the master register
        let mut val = self.read32(c::RPU_REG_INT_FROM_RPU_CTRL, None).await;

        val |= 1 << c::RPU_REG_BIT_INT_FROM_RPU_CTRL;

        self.write32(c::RPU_REG_INT_FROM_RPU_CTRL, None, val).await;

        // Now enable the relevant MCU interrupt line
        self.write32(
            c::RPU_REG_INT_FROM_MCU_CTRL,
            None,
            1 << c::RPU_REG_BIT_INT_FROM_MCU_CTRL,
        )
        .await;
    }

    #[allow(unused)]
    async fn rpu_irq_disable(&mut self) {
        let mut val = self.read32(c::RPU_REG_INT_FROM_RPU_CTRL, None).await;
        val &= !(1 << c::RPU_REG_BIT_INT_FROM_RPU_CTRL);
        self.write32(c::RPU_REG_INT_FROM_RPU_CTRL, None, val).await;

        self.write32(
            c::RPU_REG_INT_FROM_MCU_CTRL,
            None,
            !(1 << c::RPU_REG_BIT_INT_FROM_MCU_CTRL),
        )
        .await;
    }

    async fn rpu_irq_ack(&mut self) {
        // Guess: I think this clears the interrupt flag
        self.write32(c::RPU_REG_INT_FROM_MCU_ACK, None, 1 << c::RPU_REG_BIT_INT_FROM_MCU_ACK)
            .await;
    }

    /// Checks if the watchdog was the source of the interrupt
    async fn rpu_irq_watchdog_check(&mut self) -> bool {
        let val = self.read32(c::RPU_REG_MIPS_MCU_UCCP_INT_STATUS, None).await;
        (val & (1 << c::RPU_REG_BIT_MIPS_WATCHDOG_INT_STATUS)) > 0
    }

    async fn rpu_irq_watchdog_ack(&mut self) {
        self.write32(
            c::RPU_REG_MIPS_MCU_UCCP_INT_CLEAR,
            None,
            1 << c::RPU_REG_BIT_MIPS_WATCHDOG_INT_CLEAR,
        )
        .await;
    }

    async fn rpu_event_read(&mut self, event_address: u32, buf: &mut [u32]) {
        self.read(
            event_address,
            None,
            &mut buf[..c::RPU_EVENT_COMMON_SIZE_MAX as usize / 4],
        )
        .await;

        // Get the header from the front of the event data
        let message_header: &c::host_rpu_msg_hdr = unsliceit(slice8(buf));
        let len = message_header.len as usize;
        let resubmit = message_header.resubmit;

        if len > MAX_EVENT_POOL_LEN {
            todo!("Fragmented event read is not yet implemented");
        } else if len > c::RPU_EVENT_COMMON_SIZE_MAX as usize {
            // This is a longer than usual event. We gotta read it again
            self.read(event_address, None, &mut buf[..len.div_ceil(4)]).await;
        }

        // Hand the event back to the RPU only once it has been read in full.
        if resubmit > 0 {
            self.rpu_event_free(event_address).await;
        }
    }

    async fn rpu_event_free(&mut self, event_address: u32) {
        self.rpu_hpq_enqueue(self.rpu_info.as_ref().unwrap().hpqm_info.event_avl_queue, event_address)
            .await;
    }

    /// Writes one command buffer (at most [`MAX_CMD_SIZE`] bytes) and hands it to the RPU.
    async fn rpu_cmd_ctrl_send(&mut self, message: &[u32]) {
        assert!(message.len() * 4 <= MAX_CMD_SIZE);

        // Wait until we get an address to write to
        // This queue might already be full with other messages, so we'll just have to wait a bit
        let message_address = loop {
            if let Some(message_address) = self
                .rpu_hpq_dequeue(self.rpu_info.as_ref().unwrap().hpqm_info.cmd_avl_queue)
                .await
            {
                break message_address;
            }
        };

        // Write the message to the suggested address
        self.write(message_address, None, message).await;

        // Post the updated information to the RPU
        self.rpu_hpq_enqueue(
            self.rpu_info.as_ref().unwrap().hpqm_info.cmd_busy_queue,
            message_address,
        )
        .await;

        self.rpu_msg_trigger().await;
    }

    async fn rpu_hpq_enqueue(&mut self, hpq: HostRpuHPQ, value: u32) {
        self.write32(hpq.enqueue_addr, None, value).await;
    }

    async fn rpu_hpq_dequeue(&mut self, hpq: HostRpuHPQ) -> Option<u32> {
        let value = self.read32(hpq.dequeue_addr, None).await;

        // Pop element only if it is valid
        if value != 0 {
            self.write32(hpq.dequeue_addr, None, value).await;
            Some(value)
        } else {
            None
        }
    }

    async fn init_rpu_info(&mut self) {
        // Based on 'wifi_nrf_hal_dev_init'

        let mut hpqm_info = [0u32; size_of::<HostRpuHPQMInfo>() / 4];
        self.read(c::RPU_MEM_HPQ_INFO, None, &mut hpqm_info).await;

        let rx_cmd_base = self.read32(c::RPU_MEM_RX_CMD_BASE, None).await;

        self.rpu_info = Some(RpuInfo {
            hpqm_info: unsafe { core::mem::transmute_copy(&hpqm_info) },
            rx_cmd_base,
            tx_cmd_base: c::RPU_MEM_TX_CMD_BASE,
        });
    }

    /// Reads the UMAC's copy of the OTP (NCS `nrf_wifi_hal_otp_info_get`,
    /// `nrf_wifi_hal_otp_ft_prog_ver_get` and `nrf_wifi_hal_otp_pack_info_get`).
    async fn read_otp(&mut self) -> Otp {
        const WORDS: usize = size_of::<c::host_rpu_umac_info>().div_ceil(4);
        let mut words = [0u32; WORDS];
        self.read(c::RPU_MEM_UMAC_BOOT_SIG, None, &mut words).await;
        Otp {
            info: unsafe { core::ptr::read_unaligned(words.as_ptr() as *const c::host_rpu_umac_info) },
            flags: self.read32(c::RPU_MEM_OTP_INFO_FLAGS, None).await,
            ft_prog_ver: self.read32(c::RPU_MEM_OTP_FT_PROG_VERSION, None).await,
            package_info: self.read32(c::RPU_MEM_OTP_PACKAGE_TYPE, None).await,
        }
    }

    async fn send_cmd<T: Command>(&mut self, mut cmd: T) {
        cmd.fill();

        #[repr(C, packed)]
        struct Msg<T> {
            header: c::host_rpu_msg,
            cmd: T,
        }

        let mut msg = Msg {
            header: unsafe { zeroed() },
            cmd,
        };
        msg.header.hdr.len = size_of::<Msg<T>>() as _;
        msg.header.type_ = T::MESSAGE_TYPE as _;

        // A command longer than one buffer goes out in fragments, which the RPU reassembles
        // using the total length in the header (NCS `hal_rpu_cmd_queue`).
        for fragment in sliceit(&msg).chunks(MAX_CMD_SIZE) {
            let mut buf = [0u32; MAX_CMD_SIZE / 4];
            slice8_mut(&mut buf)[..fragment.len()].copy_from_slice(fragment);
            let words = &buf[..fragment.len().div_ceil(4)];
            if with_timeout(Duration::from_secs(1), self.rpu_cmd_ctrl_send(words))
                .await
                .is_err()
            {
                panic!("timed out waiting for a free command buffer");
            }
        }
    }

    /// Sends the system init command (NCS `umac_cmd_sys_init`), with the SDK's defaults for a
    /// station without low power mode.
    async fn init_umac(&mut self, rf_params: &c::phy_rf_params, config: &Config) {
        let mut rf_params_bytes = [0u8; c::RF_PARAMS_SIZE as usize];
        rf_params_bytes.copy_from_slice(sliceit(rf_params));

        let rx_buf_pool = c::rx_buf_pool_params {
            buf_sz: RX_MAX_DATA_SIZE as _, // the RPU adds the headroom itself
            num_bufs: RX_BUFS_PER_QUEUE as _,
        };
        let cmd = c::cmd_sys_init {
            sys_head: unsafe { zeroed() },
            wdev_id: 0,
            sys_params: c::sys_params {
                sleep_enable: 0, // TODO for low power
                hw_bringup_time: c::HW_DELAY,
                sw_bringup_time: c::SW_DELAY,
                bcn_time_out: c::BCN_TIMEOUT,
                calib_sleep_clk: c::CALIB_SLEEP_CLOCK_ENABLE,
                phy_calib: c::DEF_PHY_CALIB,
                mac_addr: [0; 6],
                rf_params: rf_params_bytes,
                rf_params_valid: 1,
            },
            rx_buf_pools: [rx_buf_pool; c::MAX_NUM_OF_RX_QUEUES as usize],
            data_config_params: c::data_config_params {
                rate_protection_type: 0,
                aggregation: 1,
                wmm: 1,
                max_num_tx_agg_sessions: 4,
                max_num_rx_agg_sessions: 8,
                max_tx_aggregation: MAX_TX_AGGREGATION as _,
                reorder_buf_size: 64,
                max_rxampdu_size: 3,
            },
            temp_vbat_config_params: c::temp_vbat_config {
                temp_based_calib_en: c::TEMP_CALIB_ENABLE,
                temp_calib_bitmap: c::DEF_PHY_TEMP_CALIB,
                vbat_calibp_bitmap: c::DEF_PHY_VBAT_CALIB,
                temp_vbat_mon_period: c::TEMP_CALIB_PERIOD,
                vth_very_low: c::VBAT_VERYLOW as _,
                vth_low: c::VBAT_LOW as _,
                vth_hi: c::VBAT_HIGH as _,
                temp_threshold: c::TEMP_CALIB_THRESHOLD as _,
                vbat_threshold: 0,
            },
            tcp_ip_checksum_offload: 0,
            country_code: config.country_code,
            op_band: c::op_band::BAND_ALL as _,
            // Management frames stay in the RPU instead of taking RX buffers.
            mgmt_buff_offload: 1,
            feature_flags: 0,
            disable_beamforming: 0,
            // NCS CONFIG_NRF_WIFI_AP_DEAD_DETECT_TIMEOUT, in seconds.
            discon_timeout: 20,
            ps_exit_strategy: c::ps_exit_strategy::EVERY_TIM as _,
            // The watchdog serves the SDK's RPU recovery, which comes with low power mode: off.
            watchdog_timer_val: 0xFFFFFF,
            keep_alive_enable: 0,
            keep_alive_period: 0,
            // NCS CONFIG_NRF_WIFI_DISPLAY_SCAN_BSS_LIMIT.
            display_scan_bss_limit: 150,
            coex_disable_ptiwin_for_wifi_scan: 0,
            raw_scan_enable: 0,
            // NCS CONFIG_NRF_WIFI_MAX_PS_POLL_FAIL_CNT.
            max_ps_poll_fail_cnt: 10,
            // NCS CONFIG_NRF_WIFI_RX_STBC_HT.
            stbc_enable_in_ht: 1,
            dbs_war_ctrl: 0,
            dynamic_ed: 0,
            // No coexistence with a short-range radio.
            bt_slot_time_in_ms: 0,
            bt_coex_disable: 1,
            display_scan_abort_on_bss_limit: 0,
        };
        self.send_cmd(cmd).await;
    }

    /// Sets the MAC address of the default interface (NCS `wifi_nrf_fmac_set_vif_macaddr`).
    async fn set_mac_address(&mut self, mac_addr: [u8; 6]) {
        let mut cmd: c::umac_cmd_change_macaddr = unsafe { zeroed() };
        cmd.macaddr_info.mac_addr = mac_addr;
        self.send_cmd(cmd).await;
    }

    /// Brings the default interface up and waits for the RPU to confirm (NCS
    /// `nrf_wifi_sys_fmac_chg_vif_state`).
    async fn set_interface_up(&mut self) {
        let mut cmd: c::umac_cmd_chg_vif_state = unsafe { zeroed() };
        cmd.info.state = 1;
        cmd.info.if_index = 0;
        self.send_cmd(cmd).await;

        self.wait_for_event(
            "IFFLAGS_STATUS",
            |event| matches!(event, Event::Umac(id, _) if *id == c::umac_events::UMAC_EVENT_IFFLAGS_STATUS as u32),
        )
        .await;
    }

    /// Starts a display scan (NCS `nrf_wifi_disp_scan_zep` without parameters). The zeroed
    /// parameters ask for an active scan of every channel of both bands, with the default dwell
    /// times.
    async fn trigger_scan(&mut self) {
        let mut cmd: c::umac_cmd_scan = unsafe { zeroed() };
        cmd.info.scan_reason = c::scan_reason::SCAN_DISPLAY as _;
        self.send_cmd(cmd).await;
    }

    /// Asks for the results of a finished display scan (NCS `wifi_nrf_fmac_scan_res_get`).
    async fn get_scan_results(&mut self) {
        let mut cmd: c::umac_cmd_get_scan_results = unsafe { zeroed() };
        cmd.scan_reason = c::scan_reason::SCAN_DISPLAY as _;
        self.send_cmd(cmd).await;
    }

    async fn init_tx(&mut self) {}

    async fn init_rx(&mut self) {
        for desc_id in 0..RX_BUFS {
            self.rx_buf_post(desc_id).await;
        }
    }

    /// Hands RX buffer `desc_id` to the RPU (NCS `wifi_nrf_fmac_rx_cmd_send`).
    async fn rx_buf_post(&mut self, desc_id: usize) {
        let queue_id = desc_id / RX_BUFS_PER_QUEUE;
        let rpu_addr = c::RPU_MEM_PKT_BASE + (TX_TOTAL_SIZE + RX_BUF_SIZE * desc_id) as u32;

        // write rx buffer header
        self.write32(rpu_addr, None, desc_id as u32).await;

        // Create host_rpu_rx_buf_info (it's just one word of the address)
        let command = [rpu_addr + c::RX_BUF_HEADROOM];

        // Call wifi_nrf_hal_data_cmd_send with the command
        self.rpu_rx_cmd_send(&command, desc_id as u32, queue_id).await;
    }

    async fn rpu_rx_cmd_send(&mut self, command: &[u32], desc_id: u32, pool_id: usize) {
        let addr_base = self.rpu_info.as_ref().unwrap().rx_cmd_base;
        let max_cmd_size = c::RPU_DATA_CMD_SIZE_MAX_RX;

        let addr = addr_base + max_cmd_size * desc_id;
        let host_addr = addr & c::RPU_ADDR_MASK_OFFSET | c::RPU_MCU_CORE_INDIRECT_BASE;

        // Write the command to the core. NCS writes it through the current processor, which is
        // the LMAC once the firmware has booted.
        self.rpu_write_core(host_addr, command, Processor::Lmac).await;

        // Post the updated information to the RPU
        self.rpu_hpq_enqueue(
            self.rpu_info.as_ref().unwrap().hpqm_info.rx_buf_busy_queue[pool_id],
            addr,
        )
        .await;
    }

    async fn rpu_msg_trigger(&mut self) {
        // Indicate to the RPU that the information has been posted
        self.write32(
            c::RPU_REG_INT_TO_MCU_CTRL,
            Some(Processor::Umac),
            self.num_commands | 0x7fff0000,
        )
        .await;
        self.num_commands = self.num_commands.wrapping_add(1);
    }

    /// Writes a firmware patch to `processor`'s memory at `rpu_addr`.
    async fn load_fw(&mut self, processor: Processor, rpu_addr: u32, image: &[u8]) {
        const FW_CHUNK_SIZE: usize = 1024;
        let mut buf = [0u32; FW_CHUNK_SIZE / 4];
        for (i, chunk) in image.chunks(FW_CHUNK_SIZE).enumerate() {
            // The images are not word aligned in nrf70.bin, and one has an odd length: copy each
            // chunk into a word buffer, zero padded.
            let words = chunk.len().div_ceil(4);
            buf[words - 1] = 0;
            slice8_mut(&mut buf)[..chunk.len()].copy_from_slice(chunk);
            let addr = rpu_addr + (FW_CHUNK_SIZE * i) as u32;
            self.write(addr, Some(processor), &buf[..words]).await;
        }
    }

    /// Pulses a processor's soft reset and waits for it to park at its boot exception vector
    /// (NCS `nrf_wifi_hal_proc_reset`).
    async fn rpu_proc_reset(&mut self, processor: Processor) {
        let (control, status) = match processor {
            Processor::Lmac => (c::RPU_REG_MIPS_MCU_CONTROL, 0xA4000018),
            Processor::Umac => (c::RPU_REG_MIPS_MCU2_CONTROL, 0xA4000118),
        };
        self.write32(control, None, 0x1).await;
        while self.read32(control, None).await & 0x1 != 0 {}
        while self.read32(status, None).await & 0x1 != 1 {}
    }

    /// Starts a processor on its loaded patches and waits for its boot signature (NCS
    /// `nrf_wifi_hal_fw_patch_boot` and `nrf_wifi_hal_fw_chk_boot`).
    async fn rpu_proc_boot(&mut self, processor: Processor) {
        let (boot_sig_addr, boot_sig, sleepctrl_addr, patch_offset, control, vectors) = match processor {
            Processor::Lmac => (
                c::RPU_MEM_LMAC_BOOT_SIG,
                c::LMAC_BOOT_SIG,
                c::RPU_REG_UCC_SLEEP_CTRL_DATA_0,
                c::LMAC_ROM_PATCH_OFFSET,
                c::RPU_REG_MIPS_MCU_CONTROL,
                [
                    (c::RPU_REG_MIPS_MCU_BOOT_EXCP_INSTR_0, c::LMAC_BOOT_EXCP_VECT_0),
                    (c::RPU_REG_MIPS_MCU_BOOT_EXCP_INSTR_1, c::LMAC_BOOT_EXCP_VECT_1),
                    (c::RPU_REG_MIPS_MCU_BOOT_EXCP_INSTR_2, c::LMAC_BOOT_EXCP_VECT_2),
                    (c::RPU_REG_MIPS_MCU_BOOT_EXCP_INSTR_3, c::LMAC_BOOT_EXCP_VECT_3),
                ],
            ),
            Processor::Umac => (
                c::RPU_MEM_UMAC_BOOT_SIG,
                c::UMAC_BOOT_SIG,
                c::RPU_REG_UCC_SLEEP_CTRL_DATA_1,
                c::UMAC_ROM_PATCH_OFFSET,
                c::RPU_REG_MIPS_MCU2_CONTROL,
                [
                    (c::RPU_REG_MIPS_MCU2_BOOT_EXCP_INSTR_0, c::UMAC_BOOT_EXCP_VECT_0),
                    (c::RPU_REG_MIPS_MCU2_BOOT_EXCP_INSTR_1, c::UMAC_BOOT_EXCP_VECT_1),
                    (c::RPU_REG_MIPS_MCU2_BOOT_EXCP_INSTR_2, c::UMAC_BOOT_EXCP_VECT_2),
                    (c::RPU_REG_MIPS_MCU2_BOOT_EXCP_INSTR_3, c::UMAC_BOOT_EXCP_VECT_3),
                ],
            ),
        };

        self.write32(boot_sig_addr, None, 0).await;
        // Tells the ROM where the patch starts.
        self.write32(sleepctrl_addr, None, patch_offset).await;
        for (reg, val) in vectors {
            self.write32(reg, None, val).await;
        }
        self.write32(control, None, 0x1).await;

        let booted = with_timeout(FW_BOOT_TIMEOUT, async {
            while self.read32(boot_sig_addr, None).await != boot_sig {
                Timer::after(Duration::from_millis(10)).await;
            }
        })
        .await;
        if booted.is_err() {
            panic!("{} did not boot", processor);
        }
    }

    #[allow(unused)]
    async fn rpu_wait_until_write_done(&mut self) {
        while self.bus.read_sr0().await & SR0_WRITE_IN_PROGRESS != 0 {}
    }

    async fn rpu_wait_until_awake(&mut self) {
        for _ in 0..10 {
            if self.bus.read_sr1().await & SR1_RPU_AWAKE != 0 {
                return;
            }
            Timer::after(Duration::from_millis(1)).await;
        }
        panic!("awakening never came")
    }

    #[allow(unused)]
    async fn rpu_wait_until_ready(&mut self) {
        for _ in 0..10 {
            if self.bus.read_sr1().await == SR1_RPU_AWAKE | SR1_RPU_READY {
                return;
            }
            Timer::after(Duration::from_millis(1)).await;
        }
        panic!("readyning never came")
    }

    async fn rpu_wait_until_wakeup_req(&mut self) {
        for _ in 0..10 {
            if self.bus.read_sr2().await == SR2_RPU_WAKEUP_REQ {
                return;
            }
            Timer::after(Duration::from_millis(1)).await;
        }
        panic!("wakeup_req never came")
    }

    async fn rpu_wakeup(&mut self) {
        self.bus.write_sr2(SR2_RPU_WAKEUP_REQ).await;
        self.rpu_wait_until_wakeup_req().await;
        self.rpu_wait_until_awake().await;
    }

    #[allow(unused)]
    async fn rpu_sleep(&mut self) {
        self.bus.write_sr2(0).await;
    }

    #[allow(unused)]
    async fn rpu_sleep_status(&mut self) -> u8 {
        self.bus.read_sr1().await
    }

    async fn raw_read32_inner(&mut self, mem: &MemoryRegion, offs: u32) -> u32 {
        assert!(mem.start + offs + 4 <= mem.end);
        let lat = mem.latency as usize;

        let mut buf = [0u32; 3];
        self.bus.read(mem.start + offs, &mut buf[..lat + 1]).await;
        buf[lat]
    }

    async fn raw_read32(&mut self, mem: &MemoryRegion, offs: u32) -> u32 {
        let res = self.raw_read32_inner(mem, offs).await;
        trace!("read32 {:08x} {:08x}", mem.start + offs, res);
        res
    }

    async fn raw_read(&mut self, mem: &MemoryRegion, offs: u32, buf: &mut [u32]) {
        assert!(mem.start + offs + (buf.len() as u32 * 4) <= mem.end);

        // latency=0 optimization doesn't seem to be working, we read the first word repeatedly.
        // Read word by word instead.
        for (i, val) in buf.iter_mut().enumerate() {
            *val = self.raw_read32_inner(mem, offs + i as u32 * 4).await;
        }
        trace!(
            "read addr={:08x} len={:08x} buf={:02x}",
            mem.start + offs,
            buf.len() * 4,
            slice8(buf)
        );
    }
    async fn raw_write32(&mut self, mem: &MemoryRegion, offs: u32, val: u32) {
        self.raw_write(mem, offs, &[val]).await
    }

    async fn raw_write(&mut self, mem: &MemoryRegion, offs: u32, buf: &[u32]) {
        assert!(mem.start + offs + (buf.len() as u32 * 4) <= mem.end);
        trace!(
            "write addr={:08x} len={:08x} buf={:02x}",
            mem.start + offs,
            buf.len() * 4,
            slice8(buf)
        );
        self.bus.write(mem.start + offs, buf).await;
    }

    async fn read32(&mut self, rpu_addr: u32, processor: Option<Processor>) -> u32 {
        let (mem, offs) = regions::remap_global_addr_to_region_and_offset(rpu_addr, processor);
        self.raw_read32(mem, offs).await
    }

    async fn read(&mut self, rpu_addr: u32, processor: Option<Processor>, buf: &mut [u32]) {
        let (mem, offs) = regions::remap_global_addr_to_region_and_offset(rpu_addr, processor);
        self.raw_read(mem, offs, buf).await
    }

    async fn write32(&mut self, rpu_addr: u32, processor: Option<Processor>, val: u32) {
        let (mem, offs) = regions::remap_global_addr_to_region_and_offset(rpu_addr, processor);
        self.raw_write32(mem, offs, val).await
    }

    async fn write(&mut self, rpu_addr: u32, processor: Option<Processor>, buf: &[u32]) {
        let (mem, offs) = regions::remap_global_addr_to_region_and_offset(rpu_addr, processor);
        self.raw_write(mem, offs, buf).await
    }

    async fn rpu_write_core(&mut self, core_address: u32, buf: &[u32], processor: Processor) {
        // We receive the address as a byte address, while we need to write it as a word address
        let addr = (core_address & c::RPU_ADDR_MASK_OFFSET) / 4;

        let (addr_reg, data_reg) = match processor {
            Processor::Lmac => (
                c::RPU_REG_MIPS_MCU_SYS_CORE_MEM_CTRL,
                c::RPU_REG_MIPS_MCU_SYS_CORE_MEM_WDATA,
            ),
            Processor::Umac => (
                c::RPU_REG_MIPS_MCU2_SYS_CORE_MEM_CTRL,
                c::RPU_REG_MIPS_MCU2_SYS_CORE_MEM_WDATA,
            ),
        };

        // Write the processor address register
        self.write32(addr_reg, Some(processor), addr).await;

        // Write to the data register one by one
        for data in buf {
            self.write32(data_reg, Some(processor), *data).await;
        }
    }
}

pub trait Bus {
    async fn read(&mut self, addr: u32, buf: &mut [u32]);
    async fn write(&mut self, addr: u32, buf: &[u32]);
    async fn read_sr0(&mut self) -> u8;
    async fn read_sr1(&mut self) -> u8;
    async fn read_sr2(&mut self) -> u8;
    async fn write_sr2(&mut self, val: u8);
}

pub struct SpiBus<T> {
    spi: T,
}

impl<T> SpiBus<T> {
    pub fn new(spi: T) -> Self {
        Self { spi }
    }
}

impl<T: SpiDevice> Bus for SpiBus<T> {
    async fn read(&mut self, addr: u32, buf: &mut [u32]) {
        self.spi
            .transaction(&mut [
                Operation::Write(&[0x0B, (addr >> 16) as u8, (addr >> 8) as u8, addr as u8, 0x00]),
                Operation::Read(slice8_mut(buf)),
            ])
            .await
            .unwrap()
    }

    async fn write(&mut self, addr: u32, buf: &[u32]) {
        self.spi
            .transaction(&mut [
                Operation::Write(&[0x02, (addr >> 16) as u8 | 0x80, (addr >> 8) as u8, addr as u8]),
                Operation::Write(slice8(buf)),
            ])
            .await
            .unwrap()
    }

    async fn read_sr0(&mut self) -> u8 {
        let mut buf = [0; 2];
        self.spi.transfer(&mut buf, &[0x05]).await.unwrap();
        let val = buf[1];
        defmt::trace!("read sr0 = {:02x}", val);
        val
    }

    async fn read_sr1(&mut self) -> u8 {
        let mut buf = [0; 2];
        self.spi.transfer(&mut buf, &[0x1f]).await.unwrap();
        let val = buf[1];
        defmt::trace!("read sr1 = {:02x}", val);
        val
    }

    async fn read_sr2(&mut self) -> u8 {
        let mut buf = [0; 2];
        self.spi.transfer(&mut buf, &[0x2f]).await.unwrap();
        let val = buf[1];
        defmt::trace!("read sr2 = {:02x}", val);
        val
    }

    async fn write_sr2(&mut self, val: u8) {
        defmt::trace!("write sr2 = {:02x}", val);
        self.spi.write(&[0x3f, val]).await.unwrap();
    }
}

/// This structure encapsulates the information which represents a HPQ.
#[repr(C)]
#[derive(Debug, defmt::Format, Clone, Copy)]
pub(crate) struct HostRpuHPQ {
    /// HPQ address where the host can post the address of a
    /// message intended for the RPU.
    enqueue_addr: u32,
    /// HPQ address where the host can get the address of a
    /// message intended for the host.
    dequeue_addr: u32,
}

/// Hostport queue information passed by the RPU to the host, which the host can
/// use, to communicate with the RPU.
#[repr(C)]
#[derive(Debug, defmt::Format, Clone, Copy)]
pub(crate) struct HostRpuHPQMInfo {
    /// Queue which the RPU uses to inform the host about events.
    event_busy_queue: HostRpuHPQ,
    /// Queue on which the consumed events are pushed so that RPU can reuse them.
    event_avl_queue: HostRpuHPQ,
    /// Queue used by the host to push commands to the RPU.
    cmd_busy_queue: HostRpuHPQ,
    /// Queue which RPU uses to inform host about command buffers which can be used to push commands to the RPU.
    cmd_avl_queue: HostRpuHPQ,
    rx_buf_busy_queue: [HostRpuHPQ; c::MAX_NUM_OF_RX_QUEUES as usize],
}

#[derive(Debug, defmt::Format)]
pub(crate) struct RpuInfo {
    hpqm_info: HostRpuHPQMInfo,
    /// The base address for posting RX commands.
    rx_cmd_base: u32,
    /// The base address for posting TX commands.
    #[allow(unused)]
    tx_cmd_base: u32,
}

#[cfg(test)]
mod tests {
    extern crate std;

    use core::{assert, assert_eq};
    use std::vec;
    use std::vec::Vec;

    use embassy_futures::block_on;

    use super::*;

    // The host has no RTT: defmt output goes nowhere.
    #[defmt::global_logger]
    struct NullLogger;

    unsafe impl defmt::Logger for NullLogger {
        fn acquire() {}
        unsafe fn flush() {}
        unsafe fn release() {}
        unsafe fn write(_bytes: &[u8]) {}
    }

    #[defmt::panic_handler]
    fn defmt_panic() -> ! {
        core::panic!("defmt panic")
    }

    defmt::timestamp!("");

    /// The nRF7002-DK's ceilings, from its devicetree.
    const DK_CEILING: TxPowerCeiling = TxPowerCeiling {
        dsss_2g: 21,
        mcs0_2g: 16,
        mcs7_2g: 16,
        mcs0_5g_low: 9,
        mcs7_5g_low: 9,
        mcs0_5g_mid: 11,
        mcs7_5g_mid: 11,
        mcs0_5g_high: 13,
        mcs7_5g_high: 13,
    };

    /// OTP whose crystal calibration byte is 0x2d, with the given flags and package.
    fn otp(flags: u32, package_info: u32) -> Otp {
        let mut info: c::host_rpu_umac_info = unsafe { zeroed() };
        let mut calib = [0u32; 9];
        calib[c::OTP_OFF_CALIB_XO as usize / 4] = 0x2d << (8 * (c::OTP_OFF_CALIB_XO % 4));
        info.calib = calib;
        Otp {
            info,
            flags,
            ft_prog_ver: 0xFFFF_FFFF,
            package_info,
        }
    }

    const NOT_PROGRAMMED: u32 = 0xFFFF_FFFF;

    #[test]
    fn bundled_firmware_matches_the_bindings() {
        let fw = parse_firmware(FIRMWARE);
        let images = [fw.umac_pri, fw.umac_sec, fw.lmac_pri, fw.lmac_sec];
        assert!(images.iter().all(|image| !image.is_empty()));
        let headers = size_of::<c::nrf70_fw_image_info>() + 4 * size_of::<c::nrf70_fw_image>();
        let data: usize = images.iter().map(|image| image.len()).sum();
        assert_eq!(headers + data, FIRMWARE.len());
    }

    #[test]
    fn firmware_images_fit_their_patch_regions() {
        let fw = parse_firmware(FIRMWARE);
        let patches = [
            (Processor::Umac, c::RPU_MEM_UMAC_PATCH_BIMG, fw.umac_pri),
            (Processor::Umac, c::RPU_MEM_UMAC_PATCH_BIN, fw.umac_sec),
            (Processor::Lmac, c::RPU_MEM_LMAC_PATCH_BIMG, fw.lmac_pri),
            (Processor::Lmac, c::RPU_MEM_LMAC_PATCH_BIN, fw.lmac_sec),
        ];
        for (processor, addr, image) in patches {
            let (mem, offs) = regions::remap_global_addr_to_region_and_offset(addr, Some(processor));
            // load_fw pads the last chunk to a whole word.
            assert!(mem.start + offs + image.len().next_multiple_of(4) as u32 <= mem.end);
        }
        // The secondary images end before the primary ones start.
        assert!(c::RPU_MEM_UMAC_PATCH_BIN + fw.umac_sec.len() as u32 <= c::RPU_MEM_UMAC_PATCH_BIMG);
        assert!(c::RPU_MEM_LMAC_PATCH_BIN + fw.lmac_sec.len() as u32 <= c::RPU_MEM_LMAC_PATCH_BIMG);
    }

    #[test]
    fn gram_is_read_with_two_dummy_words() {
        let (mem, offs) = regions::remap_global_addr_to_region_and_offset(c::RPU_MEM_LMAC_BOOT_SIG, None);
        assert_eq!((mem.start, mem.latency, offs), (GRAM.start, 2, 0xD50));
    }

    #[test]
    fn unprogrammed_package_gets_the_qfn_defaults() {
        let p = rf_params(&otp(NOT_PROGRAMMED, NOT_PROGRAMMED), &DK_CEILING);
        let xo = p.xo_offset.xo_freq_offset;
        let syst = p.syst_tx_pwr_offset;
        assert_eq!(xo, c::QFN_XO_VAL as u8);
        assert_eq!(syst.syst_off_lb_chan, byte(c::QFN_SYSTEM_OFFSET_LB));
    }

    #[test]
    fn csp_package_gets_the_csp_defaults() {
        let p = rf_params(&otp(NOT_PROGRAMMED, c::CSP_PACKAGE_INFO), &DK_CEILING);
        let syst = p.syst_tx_pwr_offset;
        let temp_volt = p.temp_volt_backoff;
        assert_eq!(syst.syst_off_lb_chan, byte(c::CSP_SYSTEM_OFFSET_LB));
        assert_eq!(temp_volt.hb_vbt_lt_vlow, byte(c::CSP_HB_VBT_LT_VLOW));
    }

    #[test]
    fn crystal_calibration_comes_from_otp_when_programmed() {
        let flags = c::CALIB_XO_FLAG_MASK as u32;
        let p = rf_params(&otp(flags, NOT_PROGRAMMED), &DK_CEILING);
        let xo = p.xo_offset.xo_freq_offset;
        assert_eq!(xo, 0x2d);
    }

    #[test]
    fn tx_power_ceiling_is_the_lower_of_board_and_package() {
        let p = rf_params(&otp(NOT_PROGRAMMED, NOT_PROGRAMMED), &DK_CEILING);
        let ceil = p.max_pwr_ceil;
        // Quarter dB. The board is lower here...
        assert_eq!(ceil.max_hb_low_chan_mcs7_pwr, 9 * 4);
        // ...and the package there (QFN_MAX_TX_PWR_HB_HIGH_CHAN_MCS0, 12 dBm, under the DK's 13).
        assert_eq!(
            ceil.max_hb_high_chan_mcs0_pwr,
            byte(c::QFN_MAX_TX_PWR_HB_HIGH_CHAN_MCS0)
        );
        assert_eq!(ceil.max_dsss_pwr, 21 * 4);
    }

    #[test]
    fn phy_params_are_the_sdk_defaults() {
        let p = rf_params(&otp(NOT_PROGRAMMED, NOT_PROGRAMMED), &DK_CEILING);
        let phy = p.phy_params;
        assert_eq!(phy[..5], [0x00, 0x70, 0x77, 0x00, 0x3F]);
        // Band edge backoffs, antenna gains and PCB losses stay 0.
        let edges = c::EDGE_BACKOFF_OFFSETS::BAND_2G_LW_ED_BKF_DSSS_OFST as usize - c::RF_PARAMS_CONF_SIZE as usize;
        assert!(phy[edges..edges + 34].iter().all(|&b| b == 0));
    }

    fn umac_info_with_mac(mac: [u8; 6]) -> c::host_rpu_umac_info {
        let mut bytes = [0u8; 8];
        bytes[..6].copy_from_slice(&mac);
        let mut info: c::host_rpu_umac_info = unsafe { zeroed() };
        info.mac_address0 = [
            u32::from_le_bytes(unwrap!(bytes[..4].try_into())),
            u32::from_le_bytes(unwrap!(bytes[4..].try_into())),
        ];
        info
    }

    #[test]
    fn otp_mac_address_must_be_unicast_and_programmed() {
        let mac = [0xf4, 0xce, 0x36, 0x00, 0x8b, 0x19];
        assert_eq!(otp_mac_address(&umac_info_with_mac(mac)), Some(mac));
        assert_eq!(otp_mac_address(&umac_info_with_mac([0xFF; 6])), None);
        assert_eq!(otp_mac_address(&umac_info_with_mac([0; 6])), None);
        assert_eq!(otp_mac_address(&umac_info_with_mac([0x01, 0, 0, 0, 0, 1])), None);
    }

    #[test]
    fn display_result_is_converted() {
        let mut r: c::umac_display_results = unsafe { zeroed() };
        let mut ssid = [0u8; 32];
        ssid[..4].copy_from_slice(b"test");
        r.ssid.ssid = ssid;
        r.ssid.ssid_len = 4;
        r.mac_addr = [1, 2, 3, 4, 5, 6];
        r.nwk_band = c::band::BAND_5GHZ as _;
        r.nwk_channel = 36;
        r.security_type = c::security_type::WPA3_H2E as _;
        r.signal.signal_type = c::SIGNAL_TYPE_MBM;
        r.signal.signal.mbm_signal = -7500i32 as u32;

        let bss = BssInfo::from_display_result(&r);
        assert_eq!(bss.ssid(), b"test");
        assert_eq!(bss.bssid, [1, 2, 3, 4, 5, 6]);
        assert_eq!(bss.band, Band::Band5GHz);
        assert_eq!(bss.channel, 36);
        assert_eq!(bss.rssi, Some(-75));
        assert_eq!(bss.security, Security::Wpa3);
    }

    #[test]
    fn events_are_told_apart_by_message_type() {
        let mut buf = [0u32; 8];
        let words = [
            16, // host_rpu_msg_hdr.len
            0,  // host_rpu_msg_hdr.resubmit
            c::host_rpu_msg_type::HOST_RPU_MSG_TYPE_SYSTEM as u32,
            c::sys_events::EVENT_INIT_DONE as u32, // sys_head.cmd_event
        ];
        buf[..4].copy_from_slice(&words);
        assert!(matches!(
            parse_event(slice8(&buf)),
            Event::Sys(id) if id == c::sys_events::EVENT_INIT_DONE as u32
        ));

        buf[2] = c::host_rpu_msg_type::HOST_RPU_MSG_TYPE_DATA as u32;
        buf[3] = c::umac_data_commands::CMD_RX_BUFF as u32; // umac_head.cmd
        assert!(matches!(
            parse_event(slice8(&buf)),
            Event::Data(id, _) if id == c::umac_data_commands::CMD_RX_BUFF as u32
        ));
    }

    #[derive(Debug, PartialEq)]
    enum Op {
        Write(Vec<u8>),
        Read(usize),
        Transfer(Vec<u8>, usize),
    }

    /// An SPI device that records what it is asked to do, and answers reads from `read_data`.
    #[derive(Default)]
    struct MockSpi {
        ops: Vec<Op>,
        read_data: Vec<u8>,
    }

    impl MockSpi {
        fn fill(&mut self, buf: &mut [u8]) {
            for b in buf {
                *b = if self.read_data.is_empty() {
                    0
                } else {
                    self.read_data.remove(0)
                };
            }
        }
    }

    impl embedded_hal::spi::ErrorType for MockSpi {
        type Error = core::convert::Infallible;
    }

    impl SpiDevice for MockSpi {
        async fn transaction(&mut self, operations: &mut [Operation<'_, u8>]) -> Result<(), Self::Error> {
            for op in operations {
                match op {
                    Operation::Write(buf) => self.ops.push(Op::Write(buf.to_vec())),
                    Operation::Read(buf) => {
                        self.ops.push(Op::Read(buf.len()));
                        self.fill(buf);
                    }
                    Operation::Transfer(read, write) => {
                        self.ops.push(Op::Transfer(write.to_vec(), read.len()));
                        self.fill(read);
                    }
                    Operation::TransferInPlace(buf) => {
                        self.ops.push(Op::Transfer(buf.to_vec(), buf.len()));
                        self.fill(buf);
                    }
                    Operation::DelayNs(_) => {}
                }
            }
            Ok(())
        }
    }

    #[test]
    fn bus_read_is_a_fast_read_with_a_dummy_byte() {
        let mut bus = SpiBus::new(MockSpi {
            read_data: vec![0x44, 0x33, 0x22, 0x11, 0x88, 0x77, 0x66, 0x55],
            ..Default::default()
        });
        let mut buf = [0u32; 2];
        block_on(bus.read(0x0C_1234, &mut buf));
        assert_eq!(buf, [0x1122_3344, 0x5566_7788]);
        assert_eq!(
            bus.spi.ops,
            [Op::Write(vec![0x0B, 0x0C, 0x12, 0x34, 0x00]), Op::Read(8)]
        );
    }

    #[test]
    fn bus_write_sets_the_address_top_bit() {
        let mut bus = SpiBus::new(MockSpi::default());
        block_on(bus.write(0x0C_1234, &[0x1122_3344]));
        assert_eq!(
            bus.spi.ops,
            [
                Op::Write(vec![0x02, 0x8C, 0x12, 0x34]),
                Op::Write(vec![0x44, 0x33, 0x22, 0x11]),
            ]
        );
    }

    #[test]
    fn bus_status_registers() {
        let mut bus = SpiBus::new(MockSpi {
            read_data: vec![0xFF, SR1_RPU_AWAKE | SR1_RPU_READY],
            ..Default::default()
        });
        assert_eq!(block_on(bus.read_sr1()), SR1_RPU_AWAKE | SR1_RPU_READY);
        block_on(bus.write_sr2(SR2_RPU_WAKEUP_REQ));
        assert_eq!(
            bus.spi.ops,
            [Op::Transfer(vec![0x1f], 2), Op::Write(vec![0x3f, SR2_RPU_WAKEUP_REQ])]
        );
    }
}
